### ISSUE TITLE
Audio is said to be optional but there's one place that implies that it is not

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-screen-share#101]
The spec says audio is optional (e.g. [here](https://w3c.github.io/mediacapture-screen-share/#capturing-logical-or-visible-display-surfaces and [here](https://w3c.github.io/mediacapture-screen-share/#dom-mediadevices-getdisplaymedia)), which is very much intentional, but if you follow the getDisplayMedia() steps we find a contradiction:

> The provided media MUST include precisely one track of each media type in requestedMediaTypes. The devices chosen MUST be the ones determined by the user. Once selected, the source of a MediaStreamTrack MUST NOT change.

We should clarify that in the cause of audio the audio track must not be included.

**Comment by henbos** [comment]
@jan-ivar to add a PR

**Comment by guest271314** [comment]
@henbos 

> but if you follow the getDisplayMedia() steps we find a contradiction:

Related https://github.com/w3c/mediacapture-screen-share/issues/140
