### ISSUE TITLE
Which audio constraints from mediacapture-streams are applicable?

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-screen-share#103]
For video, we list a lot of constraints. For audio, we only list restrictOwnAudio. Should we list other? [These](https://www.w3.org/TR/mediacapture-streams/#constrainable-properties) are defined in mediacapture-streams:

- volume
- sampleRate
- sampleSize
- echoCancellation
- autoGainControl
- noiseSuppression
- latency
- channelCount

**Comment by alvestrand** [comment]
The resulting stream can get everything applied to it using applyConstraint(); that's outside this spec.
Should we mandate a particular processing to these when the audio stream comes from getDisplayMedia, or are you asking if we should allow them in getDisplayMedia?
