### ISSUE TITLE
Ask for user gesture to call getDisplayMedia

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-screen-share#104]
As can be seen in https://github.com/w3c/deviceorientation/issues/57, device motion/orientation access request API might require a user gesture to call this API.

Given getDisplayMedia is a powerful and privacy sensitive API, requiring a user gesture to call that API might also make sense.
This might still be possible to do so given navigator.mediaDevices.getDisplayMedia is a fairly recent API.

**Comment by martinthomson** [comment]
I support this idea.  How we managed to allow websites to show popups without a user gesture is - in retrospect - surprising.  And a camera or microphone prompt is no less a popup than `window.alert()`.  Unfortunately those ones are so well baked in that clawing them back might be too disruptive.  This one though, I think that we have to have a gesture for.

/cc @johannhof, who is working on cleaning this stuff up.
