### ISSUE TITLE
Should the permissions UI be the first captured frame?

### ISSUE THREAD

**Issue by guest271314** [w3c/mediacapture-screen-share#108]
Relevant specification sections

> [8. Security and Permissions](https://w3c.github.io/mediacapture-screen-share/#security-and-permissions)
> 
> Display capture that includes browser windows, particularly those that are under any form of control by the application, risks violation of these basic security protections. This risk is not entirely contained to browser windows, since control channels between browser applications and other applications, depending on the operating system. The key consideration is whether the captured display surface could be somehow induced to present information that would otherwise be secret from the application that is receiving the resulting media.
> 

> [8.1 Capturing Logical or Visible Display Surfaces](https://w3c.github.io/mediacapture-screen-share/#capturing-logical-or-visible-display-surfaces)
> Capture of logical display surfaces causes there to be a potential for content to be shared that a user is not made aware of. A logical display surface might render information that a user did not intend to expose. This can be more easily recognized if this information is visible. Such means are likely ineffectual against a machine, but a human recipient is less able to process content that appears only briefly.
> 
> Information that is not currently rendered to the screen SHOULD be obscured in captures unless the application has been specifically authorized to access that content (this might require elevated permissions).
> 
> How obscured areas of the logical display surface are captured to produce a visible display surface capture MAY vary. Some applications, like presentation software, benefit from having obscured portions of the screen render the image that appeared prior to being obscured. Freezing images can cause visual artifacts for changing content, or hide the fact that content is being obscured. Note that frozen portions of a capture can be incorrectly perceived as a bug. Alternatively, obscured areas might be replaced with content that marks them as being obscured, such as a grey color or hatching.
> 

Should the permissions UI where the user selects the screen, application or tab to be captured be the first captured frame if permission is granted to share the screen?

plnkr https://run.plnkr.co/preview/cjw8nj6cv00043n67mdqj2ae4/

![getDisplayImageFirstFrame1](https://user-images.githubusercontent.com/4174848/58526760-9df00400-81bf-11e9-9f19-802e400ca5f5.png)
![getDisplayImageFirstFrame2](https://user-images.githubusercontent.com/4174848/58526771-a6e0d580-81bf-11e9-8652-ca9ac060ac60.png)

**Comment by eric-carlson** [comment]
> Should the permissions UI where the user selects the screen, application or tab to be captured be the first captured frame if permission is granted to share the screen?

Why is this necessary?

In some browsers, at least, the user prompt happens in a different process from screen capture so this would require the UA to keep the prompt visible after the user selection until screen capture has started in the capture process. This may make the UI feel sluggish, and will make the code more complex.

**Comment by guest271314** [comment]
@eric-carlson The specification does not directly address the matter of a permission UI being captured, other than relevant to security considerations as to what is being captured.

Not able to gather what your position is on the question? 

Are users expecting the permissions UI to be the first captured frame? Did not here.

**Comment by eric-carlson** [comment]
> Not able to gather what your position is on the question?

My two points, "This may make the UI feel sluggish, and will make the code more complex", are both net negatives so unless this is really needed I am not in favor.

> Are users expecting the permissions UI to be the first captured frame? Did not here.

I'm not sure we have enough experience to know what users are expecting.

**Comment by guest271314** [comment]
@eric-carlson 

> so unless this is really needed I am not in favor.

Do you mean not in favor of specifying if the screen, tab, application menu (permission UI) should be captured as the first image of a `MediaStreamTrack`?

**Comment by jan-ivar** [comment]
Firefox shows a live preview, so we would be opposed to any language that would mandate a still frame.

I'd say normally specs don't dictate UX behavior this thoroughly, unless there's a severe privacy issue.

**Comment by guest271314** [comment]
@jan-ivar Consider the use case of a screen shot https://github.com/w3c/mediacapture-screen-share/issues/107. Whether the user is expecting the permission/application menu UI to be captured or not could span from yes to no. However, if the sole purpose is the take a screen shot of an HTML element in an HTML `document` - not the permission/application menu, then the developer will have to determine if the permission UI is not displayed - how the developer determines the visibility state of the screen capture permission UI/scree menu is left to them.

Relevant to security, the permission UI/tab menu displayed not only the tab selected, but also all of the tabs, open applications, windows. If a developer is not aware of that the contents of various applications can be leaked simply by selecting a screen unrelated to the content of the screen that is not and was not intended to be selected. 

Developers and a wide range of users of browsers take screen shots and capture media for a wide range of reasons. Some of the reasons are directly related to capturing the entire contents of the current screen, and all open tabs and applications; filing bug reports, minimal complete verifiable examples. Other reasons are not directly related to the entire contents of a screen, but rather specific elements and media playback, for which capturing a permission UI is not only useless, but an artifact to find a workaround for, and exposes wholly unrelated open applications, tabs, screens to data leak, if the user is for example, not aware that all of the text they typed in a text editor or a `window` which was not intended to be capture is being captured nonetheless.

**Comment by henbos** [comment]
This API is not intended as a screenshot API, does not behave as such, and UI is up to the browser.

**Comment by guest271314** [comment]
@henbos 

> This API is not intended as a screenshot API, does not behave as such, and UI is up to the browser.

This issue is not about a screenshot API proposal. 

This issue asks is "up to the browser" UI should be specified to be the first frame or not. That is, if specified that no UI should be the first frame then browsers that do so would not be in accord with the specification if that browsers' implementation did so.

**Comment by youennf** [comment]
This thread is discussing two things here:

1. Should there be UI requirements targeted at the prompt?
I do not think we could or even should define mandatory requirements in that area.
It is often best to give flexibility for implementers since there is usually no downsides like interop issues, especially since browser UIs are still being worked on.

2. If user grants access to the screen on which the prompt is displayed, when should start the actual capture?
In particular, should the first frame of the MediaStreamTrack contain or not some UI prompt artefacts.
In general, it seems better for the prompt UI to not be captured by the newly created MediaStreamTrack, both for usability and privacy potentially (if the prompt might render some other screens at selection time for instance).

This could also somehow be extended to a selection UI triggered by the user to change the screen source while sharing.

I do not think we can make a requirement here though.
We could call out this specific issue in the Security section.

**Comment by alvestrand** [comment]
Seems good to have a recommendation not to capture the prompt, but this is in UA land, so it shouldn't be a normative statement.

**Comment by guest271314** [comment]
@alvestrand The normative statement and specification could be to add an optional flag to `getDisplayMedia()`. The case where capturing the prompt, open applications, etc. would be to demonstrate a complete, minimal, verifiable example of a procedure to reproduce a bug or outcome. The irony being that capturing a users open applications, browser tabs and windows could be considered a (security) bug by some users. Therefore, the option to _not_ include such local data in the captured stream should be normative. It is highly doubtful users that execute `getDisplayMedia()` are expecting a list of their open tabs, windows, and applications to be including in the first frame of the capture. At the bare minimum, the specification should make it clear that it is possible that not only the tab, window, or application that capture permission was granted for will be capyured, but it is also possible that information relating to tabs, windows, and applications where permission _was not_ granted to be captured can nonetheless be leaked by the implementation in the first frame of capture.
