### ISSUE TITLE
Normative security requirements ("ISSUE 1")

### ISSUE THREAD

**Issue by annevk** [w3c/mediacapture-screen-share#126]
While security consideration sections are generally non-normative in nature (it's effectively a summary), it's definitely the norm (or should be the norm) that elsewhere in the document normative requirements with regards to security are made. UI requirements with SHOULD, processing requirements with MUST.

**Comment by alvestrand** [comment]
It is good to have a section called "security and privacy considerations" that has only considerations and no MUST or SHOULD statements, and then other sections (such as "how to capture video") that have the MUST and SHOULD statements.

**Comment by alvestrand** [comment]
Elad, do you need help in doing the reshuffling here?

**Comment by eladalon1983** [comment]
Took a first stab at this with #205. PTAL.

**Comment by eladalon1983** [comment]
I have removed these normative statements, by the way, and not reinstated them elsewhere. Do you think all of these need to be repeated both as a consideration as well as a normative statement?

**Comment by annevk** [comment]
Not having looked at the specifics again in detail, you want to make sure that if a user agent implements the normative part of your specification, they end up with a secure result. It's fine to add some more nuance and guidance in the non-normative sections, but the basics ought to be good. (See also https://github.com/w3ctag/security-questionnaire/issues/88.)
