### ISSUE TITLE
Should getDisplayMedia be undefined on platforms with no support?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-screen-share#127]
A [question came up](https://stackoverflow.com/questions/58842831/check-if-browser-platform-support-screen-capturing-via-getdisplaymedia) on stackoverflow: How to detect if screen sharing is supported on a particular browser and platform? Presumably this is to avoid showing users a non-functioning button.

It turns out mobile browsers like _Chrome for Android_ and _Firefox for Android_ define the API surface, but don't actually implement it, instead always rejecting with `NotAllowedError`.

This defeats feature-detection. Should those browsers instead have left `navigator.mediaDevices.getDisplayMedia` undefined?

Unlike with camera or microphone (which *is* detectable today, modulo discussions in https://github.com/w3c/mediacapture-main/issues/612 about *maybe* lying about this for privacy reasons), this would appear to leak no net fingerprinting surface about a user's system, since sites can already browser-sniff this from the UA string.

**Comment by youennf** [comment]
It seems like a Chromium bug (is there a bug filed there?).
I am not sure the spec should say anything here.

**Comment by aboba** [comment]
@jan-ivar Agree with Youenn that this is a bug. Support for feature detection is recommended in the [Client-side API Design Principles](https://w3ctag.github.io/design-principles/#feature-detect). In this case, I see no reason to circumvent that recommendation.

**Comment by LukasKalbertodt** [comment]
There is [a bug report for Chromium](https://bugs.chromium.org/p/chromium/issues/detail?id=1038244#c2). I also just created [a bug report for Firefox](https://bugzilla.mozilla.org/show_bug.cgi?id=1624181).

**Comment by jan-ivar** [comment]
Bugs have been filed on implementations so we can close this.
