### ISSUE TITLE
Human readable error message without language info

### ISSUE THREAD

**Issue by bert-github** [w3c/mediacapture-screen-share#135]
5.1 MediaDevices Additions
https://www.w3.org/TR/2019/WD-screen-capture-20191119/#mediadevices-additions

On the numbered list, item 4, sub-item 3:
> 3. If CS contains a member whose name, failedConstraint specifies a constrainable property, constraint, applicable to display surfaces, and whose value in turn is a dictionary containing a member named max, and that member's value in turn is less than the constrainable property's floor value, then let failedConstraint be the name of the constraint, let message be either undefined or an **informative human-readable message,** and return a promise rejected with a new OverconstrainedError created by calling OverconstrainedError(failedConstraint, message). 

Is there a way to indicate the language and direction of the ‘informative human-readable message’?

How is the language chosen? Does it adapt to the user whose screen is being captured?

**Comment by dontcallmedom** [comment]
This seems equivalent to a previously discussed issue in the context of getUserMedia: https://www.w3.org/International/track/issues/465

As discussed for that previous issue, the localizability of DOM error messages (assuming it is needed) would need to be handled at the platform level, not at the individual API level.

**Comment by guest271314** [comment]
`navigator.language`?

**Comment by jan-ivar** [comment]
Closing based on similar decision in https://github.com/w3c/mediacapture-main/issues/665#issuecomment-596506363
