### ISSUE TITLE
Should fire ended track event when shared window/tab is closed.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-screen-share#136]
(Note this talks about closing the source of sharing (e.g. a tab or window), not the page JS is in).

It was reported to us in https://bugzil.la/1615282 that Chrome does this, but Firefox does not.

The spec should speak about this.

I think it makes sense to fire the `ended` event on a screen-sharing track when its source "goes away permanently", or maybe just "is closed".

This may be trickier with sources other than windows. E.g. Multiple Displays (unsure what Chrome does there). We may even want to call out windows and tabs explicitly.

**Comment by guest271314** [comment]
> It was reported to us in https://bugzil.la/1615282 that Chrome does this, but Firefox does not.

The implementations of Firefox and Chromium are not consistent.

> The spec should speak about this.

Is expected behaviour not already specified at https://w3c.github.io/mediacapture-main/#track-ended ?

> When a [`MediaStreamTrack`](https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack) _track_ **ends for any reason other than the [stop()](https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-stop) method being invoked**, the User Agent _MUST_ queue a task that runs the following steps:
> 
> 1. If the _track's_ [`readyState`](https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-readystate) attribute has the value `ended` already, then abort these steps.
> 
> 2. Set _track's_ [`readyState`](https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack-readystate) attribute to `ended`.
> 
> 3. Notify _track's_ source that _track_ is [ended](https://w3c.github.io/mediacapture-main/#track-ended) so that the source may be [stopped](https://w3c.github.io/mediacapture-main/#source-stopped), unless other [`MediaStreamTrack`](https://w3c.github.io/mediacapture-main/#dom-mediastreamtrack) objects depend on it.
> 
> 4. Fire a simple event named [ended](https://w3c.github.io/mediacapture-main/#event-mediastreamtrack-ended) at the object.
> 
> If the end of the track was reached due to a user request, the event source for this event is the user interaction event source.

**Comment by guest271314** [comment]
Apparently for `ended` event to be fired on a `MediaStreamTrack` from `getDisplayMedia()` at Nightly 76 the user needs to explicitly click "X" at => address/navigation bar => Permissions => Share the Screen => Allowed Temporarily X. 

However, the procedure cannot be used in reverse with the same UI: It does not appear to be possible to undo "Blocked Temporarily" at the Permissions section UI of Firefox/Nightly.

**Comment by jan-ivar** [comment]
Yes, it turns out this is already covered both by mediacapture-main as mentioned [above](#issuecomment-602323464), and also [this spec](https://w3c.github.io/mediacapture-screen-share/#closed-and-minimized-display-surfaces): _"When a display surface enters an inaccessible state that is permanent (such as the source application terminating), the user agent MUST queue a task that ends the corresponding media track."_

This seems sufficiently clear.
