### ISSUE TITLE
Add possibility to request the same surface stream, but with different constraints (e.g. resolution)

### ISSUE THREAD

**Issue by LukasKalbertodt** [w3c/mediacapture-screen-share#139]
We would like to give our users the option to choose the resolution of their screen recording. We also would like to offer this after the user initially approved the `getDisplayMedia` prompt. It is possible, but currently the browser always prompts the user again on each resolution change. For `getUserMedia` it's possible to avoid this problem by specifying the `deviceId` in the constraints. That way the second `getUserMedia` call returns without the user being prompted.

So  my idea:

- The video track of stream returned by `getDisplayMedia` has a `surfaceId` in the object returned by `getOptions()`. This is set to a random unguesable string, like `deviceId` of media devices.
- The `MediaTrackConstraints` object can specify a `surfaceId`. 
- If the user already once approved `getDisplayMedia` in this ... "session" (for the lack of a better word) *and* if `surfaceId` is specified in the constraints of the second `getDisplayMedia` call *and* if that `surfaceId` corresponds to a surface that is still available and was shared before, then the user does not need to (and should not) be prompted again.

What do you think? Is that a sensible idea? Or rather impossible for some reason?

**Comment by youennf** [comment]
The recommended way is probably to use MediaStreamTrack.clone/applyConstraints to get a track with the desired resolution without any further prompt. The same principle should hopefully works for getUserMedia.
Would that work for you?

**Comment by LukasKalbertodt** [comment]
Oh no, I'm so sorry! I thought I'd know the full API in this regards, but I was completely unaware of `applyConstraints`. Thanks for telling me. I tried using it, but noticed a large number of browser bugs, unfortunately. But yeah this is totally how it should work and my request is therefore useless.

I know this is not the right place for support questions, so sorry again for the noise! Will research better next time!

**Comment by youennf** [comment]
> I tried using it, but noticed a large number of browser bugs

Constraints handling is an area where browsers might need to improve in terms of consistency. Please file bugs in the related browser bug trackers.

**Comment by LukasKalbertodt** [comment]
>  Please file bugs in the related browser bug trackers.

Absolutely, I planned on doing so next week :)
