### ISSUE TITLE
Examples should be updated before FPWD

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-screen-share#14]
Section-3 seems only a placeholder at the point.  It'd be nice to update it for the FPWD.

**Comment by martinthomson** [comment]
PRs accepted.  This is the entirety of the API as it stands however.

**Comment by ShijunS** [comment]
Adding another comment given the issue is still open.  The interface definition has getDisplayMedia() under NavigatorUserMedia, while Example-1 has it under mediaDevices.  Example-1 should be updated.
