### ISSUE TITLE
ensure that a tab selected by the user is what an app really supposed to share

### ISSUE THREAD

**Issue by ikasantsev** [w3c/mediacapture-screen-share#143]
Apologies if it was already discussed previously. 

What would be a recommended way to verify that the visitor did not accidentally or intentionally selected a tab with an inappropriate contents? In a scenario when a website can initiate webRTC screen sharing, it is reasonable if this website would want to limit screen sharing only to its own FQDN.

It would help if a browser display surface could be further limited to a FQDN or FQDN list, or to 'self' only. It could be done with a declarative CSP like 

`
Content-Security-Policy: screen-sharing-allow-uri 'self'
`

or with a declarative constraint, e.g.:

`            video: {
                displaySurface: 'browser',
                logicalSurface: true,
                cursor: 'always',
                allowedURI: 'self'
            }
`

If this is not possible or desirable, it could be done with some kind of active filtering like an event requested in https://github.com/w3c/mediacapture-screen-share/issues/83.

**Comment by youennf** [comment]
I could see a web site wanting to make it easier for the user to select the current tab or a same-origin tab.
A hint to the user agent may help.
I am unclear whether the request is (or if there is a use case) to forbid user to select some surfaces.

**Comment by ikasantsev** [comment]
The request is to give a website more control of what is to be shared. Yes, it would be perfect if the website could instruct user agent to limit the list of available sources, or at least ask user agent to present same-origin tabs as the default source, but this directly contradicts with how getDisplayMedia is currently described. 

An example of a use case is a website which wants to be 100% sure that their support agents will only see the website contents. They do not want their support agents to accidentally see anything else - neither the full screen of the end user, nor other browser tabs with potentially sensitive information. Ability to limit screen sharing to 'self' or same origin tabs would help.

**Comment by youennf** [comment]
If we were to expose the URL/or a same origin flag of the captured tab, would that be sufficient for the web page to stop the capture after user selection?
Also, what if the captured tab is navigating to a different origin, either definitely or temporarily, say federated login?

**Comment by ikasantsev** [comment]
Exposing the URL or a reference to a currently shared window/document seems to be sufficient. Or you could expose same origin flag AND a url if the shared tab is on the same origin (or NULL if it belongs to a display surface other than a same origin tab). That seems to be enough.

If the captured tab is navigating to some other URL we would need an event indicating that. That event should then expose the new state of the tab - new values of the same origin flag and the URL. For example.

`    SharingSurfaceChangeEvent.newURL (Read only)` - the new URL to which the window is navigating, or NULL if the new URL does not belong to the same origin as the current document,

`    SharingSurfaceChangeEvent.oldURL (Read only)` - the previous URL from which the window was navigated, or NULL if the previous URL did not belong to the same origin as the current document. 

`    SharingSurfaceChangeEvent.isSameOriginTab (Read only)` - _true_ if the new URL belongs to the same origin as the current document. 

If the user chose a display surface other than a tab, it would be helpful if you could expose a window title of whatever is currently selected for sharing. That would give the website enough details to know if it wants to stop or pause sharing.

**Comment by guest271314** [comment]
This is not possible. 

An HTML `<video>` element can display content from `file:` protocol and any URL. That same HTML `<video>` element can enter picture in picture mode. Picture in picture window is an "Application" that can be captured with `getDisplayMedia()`. Therefore while the URL where the capture initiates can be protocol://domain.mock the captured surface can be any_protocol://any_domain.any.

**Comment by guest271314** [comment]
> An example of a use case is a website which wants to be 100% sure that their support agents will only see the website contents. They do not want their support agents to accidentally see anything else

One option at Chromium is for the user to capture "Tab". Taking the procedure a step further `unmute` and `mute` events can be attached to the `MediaStreamTrack` from "Tab" capture (https://github.com/w3c/mediacapture-screen-share/issues/141) where when no user action occurs `mute` event is fired which can be posted to server, to ensure the cursor on the stream is actually the cursor coordinates posted to server.

It might still be possible to mock a session by pre-recording captured screen and substituting the pre-captured stream for the actual window being captured using `addTrack()` and `removeTrack()`.

**Comment by guest271314** [comment]
What be more difficult to mock is beginning "Tab" capture at a specific time and using `MediaRecorder.start(timeSlice)` to post `File` objects to server where the `lastModified` property can be parsed at the server and the total number of `File` objects expected and received at server can be calculated, evaluated to coincide with the actual capture.

**Comment by jan-ivar** [comment]
> An example of a use case is a website which wants to be 100% sure that their support agents will only see the website contents. They do not want their support agents to accidentally see anything else - neither the full screen of the end user, nor other browser tabs with potentially sensitive information. Ability to limit screen sharing to 'self' or same origin tabs would help.

@ikasantsev Thanks for this use case! We're hoping to cover it with better integrated web-based presentations in w3c/mediacapture-viewport#1.

> If the user chose a display surface other than a tab, it would be helpful if you could expose a window title of whatever is currently selected for sharing. That would give the website enough details to know if it wants to stop or pause sharing.

Firefox exposes this in `track.label` atm FWIW. See https://github.com/w3c/mediacapture-screen-share/issues/128.

Please let me know if this covers your issue, so I can close it out.

**Comment by guidou** [comment]
cc @eladalon1983, who is preparing a proposal to address this for the tab case using track.label

**Comment by jan-ivar** [comment]
> > The request is to give a website more control of what is to be shared. ...
>
> We're hoping to cover it with better integrated web-based presentations in w3c/mediacapture-viewport#1.

To clarify: I think *getViewportMedia* (https://github.com/w3c/mediacapture-screen-share/issues/155) is the way forward to solving self-capture safely, and I consider any workarounds in *getDisplayMedia* to coerce a user to picking a specific source to be harmful, and counterproductive to adoption of the former.

**Comment by eladalon1983** [comment]
> > > The request is to give a website more control of what is to be shared. ...
> > 
> > 
> > We're hoping to cover it with better integrated web-based presentations in w3c/mediacapture-viewport#1.
> 
> To clarify: I think _getViewportMedia_ (#155) is the way forward to solving self-capture safely, and I consider any workarounds in _getDisplayMedia_ to coerce a user to picking a specific source to be harmful, and counterproductive to adoption of the former.

`getViewportMedia` helps for self-capture, but does not address the topics of allow-listed sites (including same-origin/same-site as special cases). I think that (issue = w3c/mediacapture-screen-share#159 / PR = w3c/mediacapture-screen-share#163) solves the problem from w3c/mediacapture-screen-share#143 satisfactorily, after incorporating @youennf's input about exposing origin. w3c/mediacapture-screen-share#163 allows arbitrary capturing apps to distinguish desired/undesired capture-targets after the user has made their uncoerced selection.
(Side-note: This is just one of several things w3c/mediacapture-screen-share#163 enables.)

**Comment by jan-ivar** [comment]
> In a scenario when a website can initiate webRTC screen sharing, it is reasonable if this website would want to limit screen sharing only to its own FQDN.

> ... their support agents will only see the website contents. They do not want their support agents to accidentally see anything else - neither the full screen of the end user, nor other browser tabs with potentially sensitive information. Ability to limit screen sharing to 'self' or same origin tabs would help.

I interpret OP as being satisfied by limiting capture to sites under the capturer's control, which seems satisfied by web-integrated capture in https://github.com/w3c/mediacapture-screen-share/issues/155.

If the concern is based around avoiding exposing sensitive information, then relying on *getDisplayMedia* could backfire. E.g. employees may have ~homepages on FQDNs. Browsers have no good way to discern a site wanting to protect its users from its employees, versus a malicious site guiding users to a sensitive-data-rendering attack page.

**Comment by eladalon1983** [comment]
I agree that `getViewportMedia` is the holy grail. And I agree that some risks remain for `getDisplayMedia` + w3c/mediacapture-handle#52. But OP's site is **already** using `getDisplayMedia`, and might continue for a while¹. I think w3c/mediacapture-handle#52 could partially mitigate some of those risks. Examining the risk of support personnel's homepages - if they have them at all, you could mitigate by hosting them cross-origin from the main site. And even if we assume it is easy to convince an end-user to type a URL and then start sharing it, the extra step is definitely valuable in that it prevents accidental oversharing. Even if tightly sealing against abuse is not achieved, I think w3c/mediacapture-handle#52 presents an appreciable improvement for OP. (Note: This is not w3c/mediacapture-handle#52's main goal. Only the last benefit of four listed atm.)

---
1. It will take some time for gVM to be standardized and implemented; probably longer than w3c/mediacapture-handle#52. And even once gVM is implemented, OP's site might not be able to deploy COI + new-header, and keep relying on gDM.

**Comment by eladalon1983** [comment]
I think the discussion here has fizzled out. We can proceed on other threads such as w3c/mediacapture-handle#52. As always, feel free to reopen. :-)
