### ISSUE TITLE
allow getDisplayMedia "granted" permission to persist during the user session

### ISSUE THREAD

**Issue by ikasantsev** [w3c/mediacapture-screen-share#144]
Please consider allowing "granted" permission to persist until the permission is either revoked by the user, or until the user session in the browser is ended (either because the user closed the browser, or because the user typed in another URL and navigated away from the website which initiated screen sharing).

The use case scenario is to allow screen sharing session to persist during page-to-page navigation across different pages of the same website, without having the user to explicitly re-grant the screen sharing permission after he or she navigated to another page. This of course is necessary only when screen sharing is active during the page unload, and the new page is of the same origin as the previous page.

An example of somewhat similar behavior would be sessionStorage in the user agent (which can persist values while the browser session is active, and clears when the session ends).

**Comment by eladalon1983** [comment]
If navigation breaks off the capture, then the user is "informed" by the user agent's UX that the capture has stopped. To start it again shortly afterwards, maybe 10s later, could be terribly surprising, and possibly have very bad consequences for the user, who might by now have loaded something quite embarrassing to the screen.

Furthermore, getDisplayMedia doesn't have "permission" in the classic sense. When the app calls getDisplayMedia, it does not know what display surface will be handed to it. The user chooses one each time. It's unclear what this proposal intends. Should the same surface be auto-selected? Ignoring edge cases (e.g. does that surface still exist?) for the moment, I don't think something like this has a chance of achieving consensus in the WG.
