### ISSUE TITLE
Add an API to share the current tab

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-screen-share#149]
Today, getDisplayMedia() lets the user pick what to share, but there are use cases where the application wants to share itself (the current tab) in which case a "pick whatever you want" prompt could result in sharing more information than is required, which is not necessarily good for security or privacy.

For example: sharing presentation slides integrated into the web app that does presentation slides. This app does not need the user to share their entire screen, increasing the possibly sensitive surfaces exposed.

Having a "share this tab" is also good for user flow in an application that is self-contained and does not interact with the rest of the user's system.

**Comment by eladalon1983** [comment]
Thanks for creating this. Mind assigning it to me?

**Comment by jan-ivar** [comment]
See my comments in https://lists.w3.org/Archives/Public/public-webrtc/2020Oct/0047.html

**Comment by guest271314** [comment]
This is already implemented at Chromium. "Application" is also implemented at Chromium. Whatever you do here do not specify `mute` and `unmute` events of `MediaStreamTrack` be fired based on user non-action, to conceal a Chromium bug that will affect downstream API's resulting in unintended consequences.

**Comment by jan-ivar** [comment]
This is now being tracked in https://github.com/w3c/mediacapture-screen-share/issues/155.
