### ISSUE TITLE
Add an API to share the specific tab 

### ISSUE THREAD

**Issue by gaer87** [w3c/mediacapture-screen-share#150]
This issue relate to #149, but there is about picking of a **current tab**. It is a good suggestion, but if an user reload a current tab, capture screen will stop and we will lose all data. To avoid it I suggest to add API, which recive the **specific tab** to capture screen.

**Comment by jan-ivar** [comment]
@gaer87 Can you elaborate on the use case? I see two ways to interpret "specific" vs "current", so I'll try addressing both.

1. If the ask is to reliably capture a [browsing context](https://html.spec.whatwg.org/#browsing-context), this risks sharing documents beyond what may be obvious to users. Users can share their browser window for this today (even dragging a tab to make it into a new one), where this risk seems more intuitive.

2. If it's about capturing past users reloading a target page, this seems unrelated to whether target == capturing page.

We seem to be converging on a solution to https://github.com/w3c/mediacapture-screen-share/issues/149 with *getViewportMedia* as the answer to web-based presentations, hopefully relegating *getDisplayMedia* to sharing system-specific (non-web) apps.

For the former, there might be a use case here for browsers to consider letting permission survive page reload.

I don't anticipate the WG making further concessions around targeting in the latter, and adding a third API seems unlikely, so I'd like to close this out or capture the use case better.

**Comment by eladalon1983** [comment]
It is unclear to me what mechanism @gaer87 proposes for indicating which specific other tab is to be shared. It's been >0.5y since the original posting, and 2 months since the last comment. I don't think the discussion is progressing. I am closing for now. Feel free to reopen.
