### ISSUE TITLE
Customize selection of display surface

### ISSUE THREAD

**Issue by hectorcastro-teamviewer** [w3c/mediacapture-screen-share#151]
Dear all, 

My question is regarding: https://www.w3.org/TR/screen-capture/#authorizing-display-capture
In point 8.2 is explicitly mentioned that: "These are non-normative recommandations only."
In Point 8.2.1 "...the getDisplayMedia API does not permit the use of constraints to narrow the set of options presented".

I agree with the security concerns, but:  **Is there any way to customize, control or design this selection window differently?
We don´t want to limit or reduce the options, but present them according to our UX guidelines...**

Any pointers to documentation, or a similar issue?

Thanks a lot!!

Hector Castro

**Comment by jan-ivar** [comment]
Hi Hector,

Sorry, no. That UX is browser-specific (looks different in each browser). Specs do not dictate browser UX, much less define APIs to alter their appearance.

If your interest is specific to sharing of web surfaces, the proposed *getViewportMedia* in #155 aims to integrate that more directly (less browser-UX).

**Comment by hectorcastro-teamviewer** [comment]
Hi Jan-Ivar

Thanks for your reply.
Best

Hector

________________________________
From: Jan-Ivar Bruaroey ***@***.***>
Date: Fri, Mar 26, 2021, 19:57
To: w3c/mediacapture-screen-share ***@***.***>
CC: Hector Castro ***@***.***>, Author ***@***.***>
Subject: Re: [w3c/mediacapture-screen-share] Customize selection of display surface (#151)


Hi Hector,

Sorry, no. That UX is browser-specific (looks different in each browser). Specs do not dictate browser UX, much less define APIs to alter their appearance.

If your interest is specific to sharing of web surfaces, the proposed getViewportMedia in #155<https://github.com/w3c/mediacapture-screen-share/issues/155> aims to integrate that more directly (less browser-UX).

-
