### ISSUE TITLE
API for Grabbing a Screenshot

### ISSUE THREAD

**Issue by eladalon1983** [w3c/mediacapture-screen-share#160]
## Problem Statement
Some apps require a mechanism for taking a screenshot of the page. The canonical use-case is a mechanism that allows an end-user to provide feedback about defects to the app. (Note: Feedback to the app, not browser, but potentially about behavior only exhibited on a given browser at a given edge-case.)

Desirable attributes of this mechanism include:
* **Accurate**: Capture what the user is seeing, not an approximation thereof.
* **Secure**: The user should be able to give informed consent to the capture, probably with a preview of what was captured.
* **Ergonomic**: The user should not be able to choose the wrong thing. Extensions should not be required (discussed below).
* **Efficient**: Long processing times by the app are undesirable.
* **Economic**: When it comes to app size, less is more. Not requiring a JS library is nice.

## State of the Art
There is no current API for grabbing screenshots.

**Existing workarounds include:**
* Redrawing the DOM onto a canvas, then grabbing an image off of the canvas.
  *  Inaccurate, especially with respect to grabbing cross-origin content (usually impossible). But even for same-origin content, it is not guaranteed that the user's issue will still be observable once content is redrawn.
  * Inefficient and uneconomic.
* Using `getDisplayMedia`.
  * Insecure - encourages the user to overshare; sharing can exceed the single intended frame by quite a lot of time, and the user might not realize (due to a lack of understanding of app/browser separation).
  * Unergonomic - for both the user as well as the app. The user has to choose between multiple sources rather than just approve a single frame; the app has to worry that the user might share the wrong thing. (This also creates additional legal liability for the app over user sharing wrong thing and getting is stored by the app's back-end.)
* Extensions.
  * Insecure - could require more permissions than intended. (E.g. could grab a video at any time, rather than a screenshot at user-approved times.)
  * Unergonomic - installing an app just to take a single screenshot is problematic.
* Requiring the user to manually grab a screenshot and upload it.
  * Unergonomic - grabbing screenshots is beyond some users' technical abilities, and even savvy users find it a needless hassle.

**Interest in this feature is showcased by:**
1. Existence and adoption of JS libraries to support the work-around via the redraw-onto-canvas workaround (e.g. [html2canvas](https://github.com/niklasvh/html2canvas)).
2. Known popular apps that provide this functionality via a work-around. (Most consumer-facing Google products; e.g. Meet, Docs, Slides. Search for "help X improve" or "send feedback" on any of these applications.)
3. Previous discussions this has previously spawned in this WG (e.g. issue #107, issue #145).

## Suggested Solution
* Introduce a new API for capturing a screenshot. The API will return a promise that resolves with either a rejection or with the captured image.
* The captured image is shown to the user before it's handed over to the application.
  * The user can reject sharing the captured image with the application.
  * The user can manually crop the image (in the browser, prior to handing it to the application).
  * The user can black-out certain parts of the image (in the browser, prior to handing it to the application).

## Security Concerns
* This allows bypassing origin-isolation. However, we already allow this with `getDisplayMedia` (and soon `getViewportMedia`); this new API will provide a less dangerous version of gVM, because (a) the captured image is presented to the user for approval, and (b) capture does not proceed in the background. Requiring mitigations similar to those of gVM could be discussed. (I hope we'll be able to use less, though, but we can start out conservative.)
* There is some concern that the user might not be able to visually inspect all that they're approving, via careful manipulation of cross-origin content's opacity, rendering it imperceptible to the user, but clearly readable by a machine. I believe this to be a minor concern, as the highly user-driven nature of this API makes it unlikely that the user would approve capture by a malicious site. Also, this is a lower concern than with gDM/gVM, where multiple frames can be captured, even long after the user forgets that they had approved a capture.

## TBD Details
Everything is open to discussion, but I would like to especially invite discussion over some points:
1. Maybe the user-agent MAY/SHOULD/MUST allow the user to manually re-grab a new snapshot. This makes the process even more user-driven.
2. How do we prevent spamming the user with requests on the one hand, while not blocking the user from rejecting a snapshot only to grab a new one after interacting with the page again? Imagine the user rejects to adjust something, then asks again. I have two ideas - throttle if the user clicks "don't ask again for this page," or throttle automatically, but show the user where in the browser they could re-enable asking again. Might be out-of-scope for the WG to mandate these, but knowing that UAs have options beyond the spec would give us confidence in our decision to ignore this issue in the spec.

## Potential Compromises
Should we find ourselves struggling to reach consensus, I think we could consider providing a partial solution, then iterating. Namely:
* Can initially limit the API to single-origin applications. (Open to MAY/SHOULD/MUST.)
* Can initially mandate black-out cross-origin iframes and/or resources. (Open to MAY/SHOULD/MUST.)

**Comment by dontcallmedom** [comment]
an alternative (or a complement) to a new API might be a new value `screen` (in addition to `user` and `environment`) in the [`capture`](https://w3c.github.io/html-media-capture/#the-capture-attribute) attribute of the `<input file>` element that would trigger a UI to take and edit a screenshot.

**Comment by eladalon1983** [comment]
Thanks @dontcallmedom. This sounds like a good complement to me. I believe it would work, but my reservation for making it the only option is that it makes activation awkward from, for example, browser-based games. One would have to create a `hidden` <input> element and then then trigger a `click()` on it in response to some in-game user interaction. But maybe that's a common pattern? Wdyt?

It's just occurred to me that I was implicitly assuming the screenshot is of the current tab's contents. Expanding this to **other** tabs/windows/screens is probably premature. With **current** tab/window/screen, each option is a subset of the next option, so tab is the safest.  If `captureScreenshot()` accepts an enum/string of `tab/window/screen`, I think that will be good. (Chrome's main interest right now is in tab, btw. If other sources are problematic, we can save them for a later iteration.)

**Comment by eladalon1983** [comment]
I have an early draft of a proposal [here](https://eladalon1983.github.io/mediacapture-screenshot/).

**Comment by jan-ivar** [comment]
> The canonical use-case is a mechanism that allows an end-user to provide feedback about defects to the app.

If this is the only use-case then the following might suffice:
```js
const [track] = (await navigator.mediaDevices.getViewportMedia()).getVideoTracks();
const imageBitmap = createImageBitmap(await new ImageCapture(track).takePhoto());
track.stop();
```
The security properties don't seem significantly different to me.

> an alternative ... might be a new value screen ... in the capture attribute of the <input file> element

That might work too, but we'd want to require site-isolation and html-capture opt-in, just the same, I think.

**Comment by eladalon1983** [comment]
> If this is the only use-case then the following might suffice:

A similar workaround is discussed in [§ 4.2.1](https://eladalon1983.github.io/mediacapture-screenshot/#workarounds-using-get-display-media) of my proposal. (Section numbering could change over time - I am referring to the section for gDM-based workaround.) I agree that with `getViewportMedia`, that workaround is much improved, but I still think a bespoke API still makes sense - discussed below.

> The security properties don't seem significantly different to me.

When approving `getViewportMedia`, the user would be giving permission to capture an arbitrary number of frames, and each one is handed off to the application before the user has the time to inspect them, let alone modify them. The application might even capture two radically different frames and present only one of them to the user as a way to mislead them.

It would be a shame to "educate" otherwise savvy users, who understand the dangers of approving video-capture of a screen, that "sometimes you simply have to accept video capture."

> we'd want to require site-isolation and html-capture opt-in, just the same, I think

I will defer taking a strong position here until I've had time to discuss the matter with Chrome Security. Until then, I hope I can convince you that this topic is orthogonal to the questions of (1) desirability and (2) shape of the API.

**Comment by jan-ivar** [comment]
> > The security properties don't seem significantly different to me.
> 
> When approving getViewportMedia, the user would be giving permission to capture an arbitrary number of frames, and each one is handed off to the application before the user has the time to inspect them, let alone modify them. The application might even capture two radically different frames and present only one of them to the user as a way to mislead them.
> 
> It would be a shame to "educate" otherwise savvy users, who understand the dangers of approving video-capture of a screen, that "sometimes you simply have to accept video capture."

Our mandate is to _fix_ the _"dangers of approving video-capture"_, not educate users to stay away from it.

The _"dangers"_ in *getViewportMedia* are mitigated by site isolation, capture opt-in and permission prompt. I think that's sufficient. But if you don't then I'm listening.

> > we'd want to require site-isolation and html-capture opt-in, just the same, I think
> 
> I will defer taking a strong position here until I've had time to discuss the matter with Chrome Security. 

Let's order the possible APIs by LOW to HIGH risk:
 1. captureScreenshot() (isolated + opt-in)
 2. getViewportMedia() (isolated + opt-in)
 3. captureScreenshot() (not isolated)
 4. getDisplayMedia() (not isolated)

If you're arguing for 3, based on it being safer than 4, then I don't think that warrants a new API, because it's worse than 2.

**Comment by eladalon1983** [comment]
Before I dive into the security discussion - if your position happens to be "I would support this if we just add the requirements of isolation and opt-in," then I would be gratified to hear that explicitly. If that's the case, I think we can set to work on nailing down all of the other details, and leave this one particular topic for later.

---

I am not sure yet if I am arguing for 1 or 3; this remains to be decided. Security is of course important, but it's always a trade-off between what we're willing to risk and what we're seeking to gain. I am not yet convinced that isolation + opt-in is a silver bullet that must be fired at every target. I think in some specific circumstances, other mechanisms can stand in. Have you read [this part](https://eladalon1983.github.io/mediacapture-screenshot/#dom-mediadevices-capturescreenshot) of my document, btw? Namely:

4. The user agent SHOULD inspect the DOM and return a rejected promise if suspicious behavior is detected. Some examples of suspicious behavior include:
   * An overlaid cross-origin iframe at an opacity that's likely to escape the user's notice.
   * An overlaid cross-origin iframe displayed inside the viewport using a suspicious size in a way that the user agent suspected might be intended to escape the user's notice.

The above is a proposal for placing on the user agent the burden of detecting malicious behavior. The user agent can be as zealous in its application of this principle as it wishes, up to disallowing screenshots if any amount of opacity is utilized for anything that's not patently benign.

Another mechanism I have there is this:
* The user agent SHOULD add a random delay between when captureScreenshot() is called and when the screenshot is taken and presented to the user. This makes it harder for a malicious application to flash new content to the screen exactly at the time that the preview is presented to the user, thereby escaping the user's notice and gaining their approval of the screenshot based on the content they saw before the preview was presented.

I am curious to hear your thoughts.

**Comment by jan-ivar** [comment]
> if your position happens to be "I would support this if we just add the requirements of isolation and opt-in," then I would be gratified to hear that explicitly. If that's the case, I think we can set to work on nailing down all of the other details, and leave this one particular topic for later.

As I [stated](https://github.com/w3c/mediacapture-screen-share/issues/160#issuecomment-821562028), *getViewportMedia* seems sufficient to me for this use case. Any benefits of an API that goes even further, while they may be real, seem marginal from where we are today, so I'd suggest we revisit that value proposition once we have *getViewportMedia*.

Since we haven't ironed out COOP+COEP+html-capture yet, I'd like to solidify implementer buy-in around *getViewportMedia* first, so we don't miss that crucial step. That seems to be the hard part that's going to require effort and focus next.

Once we have that investment in place, it seems appropriate to entertain the various new APIs such buy-in enables, without any risk of API shapes ending up implemented with a subset of the necessary requirements.

> The user agent SHOULD inspect the DOM and return a rejected promise if suspicious behavior is detected. Some examples of suspicious behavior include:
> 
>   * An overlaid cross-origin iframe at an opacity that's likely to escape the user's notice.
>   * An overlaid cross-origin iframe displayed inside the viewport using a suspicious size in a way that the user agent suspected might be intended to escape the user's notice.

Thanks for this level of detail! — Unfortunately, I don't think "suspicious behavior" is normatively implementable in a web compatible way. Also, it's probably premature to review PRs for something we haven't achieved rough consensus on. We normally try to arrive at rough consensus before requiring or diving into this level of detail. That said, with site-isolation and opt-in in place, I'm not overly worried about cross-origin iframes, I think.

**Comment by eladalon1983** [comment]
@jan-ivar, I think we have two key disagreements:
1. I don't think cross-origin isolation and/or opt-in would remove the need for in-browser blacking out or otherwise censor content prior to handing it over to the application.
2. I strongly disagree over the characterization of this API's benefits as "marginal." Almost all Google products use this. Facebook approximates this by asking the user to take a screenshot manually. There exists very popular libraries for approximating this by walking the DOM. I think we have plenty of signals that the Web wants this.

**Comment by jan-ivar** [comment]
> I am not sure yet if I am arguing for 1 or 3

@eladalon1983 This is making it hard to have a meaningful conversation about security, and risks confusing things. I propose we table this until we've made progress on the viewport capture security story. We still have lots to sort out there first.

> 1. I don't think cross-origin isolation and/or opt-in would remove the need for in-browser blacking out or otherwise censor content prior to handing it over to the application.

If that's true it would be a severe blow to the *getViewportMedia* security story. Would love to hear the threat model.

**Comment by guidou** [comment]
> > 1. I don't think cross-origin isolation and/or opt-in would remove the need for in-browser blacking out or otherwise censor content prior to handing it over to the application.
> 
> If that's true it would be a severe blow to the _getViewportMedia_ security story. Would love to hear the threat model.

I think in-browser blacking out would be very useful to file feedback on a site that provides end-to-end encrypted chat and the user does not want to share sensitive content irrelevant to the bug. I don't think cross-origin isolation would help in this case.

**Comment by eladalon1983** [comment]
> > I am not sure yet if I am arguing for 1 or 3
> 
> @eladalon1983 This is making it hard to have a meaningful conversation about security

I suggest reading "I am not sure" as "I might conceivably end up agreeing with you fully by the time we reach this topic." I suggest that we use the working assumption that cross-site isolation and opt-in are requirements for captureScreenshot.

So far [you have agreed](https://github.com/w3c/mediacapture-screen-share/issues/160#issuecomment-821562028) that captureScreenshot is lower risk than getViewportMedia if the same security requirements are applied. But you also [called the benefit "marginal"](https://github.com/w3c/mediacapture-screen-share/issues/160#issuecomment-821686240) and did not agree captureScreenshot was even desirable. I think these are much more significant blockers for consensus than the specific security-gating for this feature. I think we should tackle this first.

In fact, here is my entire roadmap for building consensus here.
1. **Reach consensus that captureScreenshot is desirable; abort otherwise.**
2. Decide whether captureScreenshot should be allowed to capture on the current tab, or if it may also capture the current window. (In either case, avoid discussing monitor for the time being; it's too tricky.)
3. Decide on specific security requirements to gate the API behind. (Note the dependence of this on the previous one.)

Let's not have the cart before the horse. Let's concentrate on the first bullet-point. Under the working assumption that we only capture the current tab's viewport, and that all security measures from getViewportMedia apply to captureScreenshot - do we agree that the screenshot API carries significant enough benefits to be discussed? Please recall:
1. The user gives permission that is inherently time-bound, unlike with gVM.
2. The user is **not** taught the "un-lesson" that sharing video is par for the course.
3. The user gets to scrutinize the single frame that is captured. (This implicitly hints to the user that this is a risky operation.) 
4. The user gets to crop and black-out sensitive content, including user-generated content unique to the site. (Thank you @guidou for the chat example.)

**Comment by alvestrand** [comment]
Note - I think permission is a very reasonable thing to require for "screenshot" (probably a separate permission from anything else). I think site isolation is *not* a requirement, given that the user is going to see the content before sharing, and requiring site isolation would prevent screenshot from capturing what's actually on the screen for any non-isolated page.

**Comment by annevk** [comment]
I think it is a requirement and @jan-ivar is right that if you solve gVM you solve this. The UI proposal seems good and we should definitely have that, but we should not expect the user to be able to discern cross-origin information leaking that might be harmful to them in some way.

**Comment by guidou** [comment]
I don't think solving gVM solves this use case. For sites that provide end-to-end encrypted services, the ability for the user to remove sensitive content before sharing it unencrypted with the site is essential. Site isolation does not solve that.

**Comment by annevk** [comment]
That use case is not part of OP, but if included I'd still argue that the gVM requirements are a minimum requirement for this. To address use cases such as yours there would be additional UI requirements.

**Comment by dontcallmedom** [comment]
let me try to summarize where I think the contention is:
* gVM clearly can be used as a fallback to generate a screenshot (as @jan-ivar described it through a one-liner), and has the benefit of protecting users from hard-to-understand (and likely hard-to-spot) cross-origin attacks. 
* A dedicated getScreenshot API would allow a different UX which lets users review & redact the screenshot to remove information they know are sensitive or simply not relevant to the screenshot (e.g. imagine screenshotting due to a display bug in a teleconferencing app - no need to send the faces of the participants or their chat messages to report the bug in most cases).

The question is thus whether the risks of a cross-origin attack via a dedicated UX (including a redaction step) are sufficiently limited to make it usable without cross-origin isolation. It's a bit hard to know how willing people would be share screenshots with web sites, but I can easily imagine social engineering based on it.

**Comment by jan-ivar** [comment]
I think that's a fair summary.

My concern is trusting users to recognize or even be aware of potential attacks. Expecting users to detect something abnormal when the very use case is to report something abnormal, seems flawed.

**Comment by eladalon1983** [comment]
I recognize the benefits of requiring `cross-origin isolation + opt-in`, as well as the deficiencies of stand-in security measures. It is for that reason that I have not fully formed an opinion on the matter.

I know malicious sites regularly mislead users with false promises of salacious media content and free cryptocurrency. I can imagine how such a site could trick the user into grabbing a screenshot. For example, by feigning breakage right before the advertised payoff moment, then suggesting the user file feedback, purporting this would lead to a human operator interceding and unlocking the coveted prize.

It is unclear to me if such attacks require inordinate credulity of the user, beyond what we can reasonably protect against[*], or if these attacks are within our mandate to stop. I might also be overlooking stronger social-engineering attacks. There are people at Google whose job it is to make such judgements, and I intend to seek their counsel before taking a position.

--
[*] Under the assumption that this protection comes at the cost of greatly inconveniencing legitimate users by blocking access to useful APIs under legitimate scenarios.

**Comment by jan-ivar** [comment]
A site could do [this](https://jsfiddle.net/jib1/hxzs3to0/show) for example.

**Comment by eladalon1983** [comment]
> A site could do [this](https://jsfiddle.net/jib1/hxzs3to0/show) for example.

IIUC, this is an argument against attempting to detect suspicious behavior through low opacity. The demo demonstrates another attack, and implies that there are too many tricks for us to write heuristics against. It is a good argument and I take the lesson to heart.

A question remains - what social-engineering could be employed to convince the user to approve a screenshot, and would such social-engineering trick a reasonable user?

**Comment by dontcallmedom** [comment]
“show us you've solve this on-screen puzzle and you may win the 10K prize!”
or similarly, a pseudo-lottery win, virtual jackpot machine, etc. Combined with phishing, it would probably trick a lot of people.

**Comment by eladalon1983** [comment]
Moving away from this proposal and towards [#193](https://github.com/w3c/mediacapture-viewport/issues/2).
Edit: [#193](https://github.com/w3c/mediacapture-viewport/issues/2) has now moved to [mediacapture-viewport/issues/2](https://github.com/w3c/mediacapture-viewport/issues/2).
