### ISSUE TITLE
overconstrained event is referenced in "Constrainable Properties for Captured Display Surfaces"

### ISSUE THREAD

**Issue by guidou** [w3c/mediacapture-screen-share#168]
This event and its related behavior (muting overconstrained tracks) was removed from mediacapture-main long ago.

**Comment by eladalon1983** [comment]
Is [this OverconstrainedErrorEvent](https://w3c.github.io/mediacapture-main/archives/20170828/getusermedia.html#dom-overconstrainederrorevent) perhaps what was meant?

**Comment by eladalon1983** [comment]
It bisects [here](https://github.com/w3c/mediacapture-main/issues/573).
