### ISSUE TITLE
Share Audio in the screen share is not cming

### ISSUE THREAD

**Issue by panimozhi** [w3c/mediacapture-screen-share#194]
We have added the constraint saying audio as true and see the checkbox("Share system audio") in the prompt.

Code:
let mediaStream = await navigator.mediaDevices.getDisplayMedia({video:true**,audio:true**});

But if the option checked we are not able to see the screenshare window in another person browser.

**Comment by eladalon1983** [comment]
> But if the option checked we are not able to see the screenshare window in another person browser.

I do not understand this line. Could you please clarify?

**Comment by jan-ivar** [comment]
@panimozhi Please note this issue tracker is for issues with the specification. It sounds like you are experiencing issues with a particular browser. Please file an issue with that browser vendor instead.
