### ISSUE TITLE
How to detect Display Surfaces Minimized 

### ISSUE THREAD

**Issue by Deuscx** [w3c/mediacapture-screen-share#198]
[Screen Capture](https://www.w3.org/TR/screen-capture/#hidden-display-surfaces) it said that when Display Surfaces enters an inaccessible state will set the muted state to be true. i've tried listen the unmute event `track.onunmute` and `onmute`. but it didn't fired

**Comment by eladalon1983** [comment]
This GitHub repo is a good place to discuss the specification itself. Please file a bug with the relevant browser vendor. (But note that the spec says user agents **MAY** consider a minimized tab as inaccessible and therefore muted. So no real bug here afaict.)
