### ISSUE TITLE
Application vs. browser

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#2]
Feedback from discussions today was that the distinction between "browser tab" and "application window" was not something that was completely obvious. While the distinction is still relevant from an implementation perspective, the suggestion was to remove the differentiation in the user consent dialog and the API.

This avoids applications needing to be able to know, a priori, whether an application is needed vs. the browser. For those apps that have access to browser sharing, that would allow us to show a unified selection dialog (using crosshair-based selection complicates things a little, but we are unlikely to start with that).

**Comment by martinthomson** [comment]
@keithgrif says: 
Is the concern that if a browser has multiple tabs open that you want the user to be able to choose a specific one to share but not advertise/display the title of other tabs?

**Comment by martinthomson** [comment]
One concern that Patrick L raised was that application sharing is less good from a surprise/security perspective. We want to ensure that sharing is appropriately scoped.

Say that you have PowerPoint with several decks open. It might be that when you select the "application" for sharing, material from a window you don't intend to share might be visible. That's not a positive experience. This is exacerbated by the poor selection process (a drop-down) that we are going to see for a while yet.

The browser is similar. Sharing the entire browser means that you can't switch tabs. It also means that you inadvertently share tab titles. A narrower share avoids problems of this nature in the browser context.

**Comment by keithgrif** [comment]
While it is true from a surprise perspective (the user does not always control which application window will share) it is desirable to share specific applications in order to continue share through different application modes. An example is powerpoint when moving between edit and slideshow mode. Sharing an entire application context is desirable. It would also be useful for mobile share scenarios where specific apps would be shared.

**Comment by martinthomson** [comment]
It is my hope that a combination of things can mitigate this.
1. Treat application sharing as a special class of window, giving the browser some discretion over when or if this is enabled.
2. Have the application mode switch problem solved by the browser. If switching to fullscreen results in a different logical window at the os level, the browser can detect that and switch the sharing target.
