### ISSUE TITLE
What is the expectation when the "application" has multiple window areas?

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-screen-share#25]
When the displaySurface is set to "application", is the user agent expected to produce multiple video streams (i.e. mediastreamtracks), one for each application window?  It can be complicated when the number of windows can change during runtime or the lifetime of each window can vary.  It'd be more challenging if we want to preserve the relative positions of the windows.  It might be easier in some cases for the web developer to choose the "window" or "monitor" surfaceType instead.

**Comment by martinthomson** [comment]
I'm actually not that keen on the idea of application sharing for all of those reasons.  However, the simplest approach is to share a desktop, showing all of the windows with their current position (including z-order) and leaving the rest of the frame in some neutral colour (Firefox chooses black).

The specification currently allows for some variation in this by only saying that the windows are composited into a single video stream.  If you don't care about relative position of windows, you could tile the windows.
