### ISSUE TITLE
Define max frameRate constraint behavior when set to 0

### ISSUE THREAD

**Issue by beaufortfrancois** [w3c/mediacapture-screen-share#253]
I've noticed screen-capture web platform tests at https://github.com/web-platform-tests/wpt/blob/3728473b8ef5c7f382547d0809fe2d176c254f4c/screen-capture/getdisplaymedia.https.html#L174 say that `getDisplayMedia({video: {frameRate: {max: 0}}})` should fail with `OverconstrainedError`.

Looking at the [spec](https://w3c.github.io/mediacapture-screen-share/#dfn-framerate) though, it's not clear what the behavior should be.

![image](https://user-images.githubusercontent.com/634478/198532304-fec9b8e0-4c21-4939-8c68-d37ff9134b34.png)

One could argue that the browser could decide to make this call succeed but not send any video frames (Chromium does that), on the other hand the browser could also simply fail as not sending video frames could be seen as no-op (Firefox and Safari do that).

See https://wpt.fyi/results/screen-capture/getdisplaymedia.https.html?label=experimental&label=master&aligned
![image](https://user-images.githubusercontent.com/634478/198531878-f4226261-d9b6-401b-b11c-cbc8b5c830f2.png)

**Comment by youennf** [comment]
The spec says:
- Reject if dictionary contains a member named max, and that member's value in turn is less than the constrainable property's floor value (https://w3c.github.io/mediacapture-screen-share/#dfn-floor-value step 7.3)
- Floor value MUST be greater than zero. (https://w3c.github.io/mediacapture-screen-share/#dfn-floor-value)

It seems to me the spec mandates the rejection for { max: 0 }, but may allow {max: 0.1}.

**Comment by beaufortfrancois** [comment]
Thank you @youennf! I'll do my best to make Chromium spec-compliant then.
