### ISSUE TITLE
no-focus-change is misleading

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-screen-share#263]
"no-focus-change" name induces that there is no focus change.
This is only true for UA surface pickers, but not necessarily for OS surface pickers.

For instance, the spec says:
```
If controller.[[[FocusBehavior]]](https://w3c.github.io/mediacapture-screen-share/#dfn-focusbehavior) is "[no-focus-change](https://w3c.github.io/mediacapture-screen-share/#idl-def-CaptureStartFocusBehavior.no-focus-change)", focus the [display surface](https://w3c.github.io/mediacapture-screen-share/#dfn-display-surface) representing the capturing document.
```

Should we rename it to `focus-capturing-surface` or something more meaningful?

**Comment by eladalon1983** [comment]
This is already used in some Web apps. I'd rather not break them solely for the purpose of getting a better name. What about aliasing? Is that a practice that has some precedents? If so, I'd be open to that.

**Comment by youennf** [comment]
Another approach would be to have 'focus-capturing-surface', 'focus-captured-surface' and 'no-focus-change', the latter being changed to mean `do the default UA action`.

**Comment by eladalon1983** [comment]
It's a compelling idea, but I suspect most Web developers would understand `'no-focus-change'` as "focus will not change away from my app."

**Comment by youennf** [comment]
'no-focus-change' can mean `ensure no focus change happens` or `ensure to not trigger any focus change`. Whatever we do, it is ambiguous. Hence why I would favour renaming it to be clearer.
Keeping it would mostly keep it backward compatibility really, and I am not sure this is such a big deal since the API shipped not so long ago.

**Comment by eladalon1983** [comment]
> Keeping it would mostly keep it backward compatibility really, and I am not sure this is such a big deal since the API shipped not so long ago.

This argument puzzles me. The API shipped in Chrome m109, which was released nearly 3 months ago. Web apps have started using it. Even if we changed things today, it would be 2 more months before a new Chrome version comes out with the new enums, for a total of 5 months. Yet more Web apps will come to rely on it in the intervening time. How is it "not a big deal" to break them?

**Comment by youennf** [comment]
I am not talking about breaking these apps in 2 months from now.
I am talking about deprecating this value and removing it some time after the deprecation is done.

**Comment by eladalon1983** [comment]
@jyasskin, any thoughts?

**Comment by eladalon1983** [comment]
I think we could add `'focus-capturing-surface'`. (Or similar name. How about `'focus-capturing-application'`?)
Wrt deprecating `'no-focus-change'`, maybe we could specify that it leaves the focus with whatever was focused as a result of the interaction with the UA or OS?

**Comment by youennf** [comment]
Good, it seems we might be able to reach consensus.
@aboba, can we put that at the agenda for next's interim?
I can put a slide or two with the various approaches.

**Comment by eladalon1983** [comment]
FYI that I won't make the April interim, but I can do May. Up to you.

**Comment by youennf** [comment]
Actually, we did not discuss this issue. We should probably do it at next interim. @eladalon1983, wdyt?

**Comment by youennf** [comment]
@aboba, can you add it to June agenda?

**Comment by eladalon1983** [comment]
For the record, adding `'focus-capturing-application'` without even waiting for the interim would be fine by me. I think we should move a bit more of our activity to either GitHub or a mailing list or any other form that allows more rapid progress.

**Comment by eladalon1983** [comment]
@youennf, do you want to reopen this issue or keep it open in favor of #271?
