### ISSUE TITLE
SystemCursorEvent and cursor customization cursor

### ISSUE THREAD

**Issue by jozefchutka** [w3c/mediacapture-screen-share#267]
It would be really useful to have an option to customize cursor appearance during capturing. My idea is having a default system cursor removed using existing `.getDisplayMedia({video: {cursor: "never"}})` and a custom one added in postproduction or live / onflight with the help of a new SystemCursorEvent API.

### Use Case

Consider (these days very popular) video tutorials where one records himself + screen. This is possible with current APIs, however the missing part is to have an option to provide nice big bold custom cursor. As an example, have a look at some videos in https://www.screen.studio/

### SystemCursorEvent Proposal

- Have an API that would provide cursor events live during capturing.
- These events should provide **x, y** coordinates relative to the currently captured area
- ...**type** of system cursor currently being in use (i.e. these https://developer.mozilla.org/en-US/docs/Web/CSS/cursor ).
- ...a pressed **button** (i.e. similar to https://developer.mozilla.org/en-US/docs/Web/API/MouseEvent/button )
- ...a **timestamp** somehow related to capture start so events can be eventually synced with recording video in postproduction
- Events should only get triggered on change (x, y, type, button)

### Security

Considering user already granted access to the screen capturing and cursor appearance is not within his control anyway (dev controls `.getDisplayMedia({video:{cursor:...}})`) there is no additional information being "leaked" from a system.

API could be also restricted to provide events only when cursor appears within captured area / on captured surface.

**Comment by eladalon1983** [comment]
> Have an API that would provide cursor events live during capturing.

There [Screen Capture Community Group](https://www.w3.org/community/sccg/) has a [spec draft](https://screen-share.github.io/mouse-events/) for this. Igalia is currently implementing it in Chrome ([first CL](https://chromium-review.googlesource.com/c/chromium/src/+/4517372)). Your support would be welcome on [this thread](https://github.com/screen-share/mouse-events/issues/6). And you're welcome to [file issues](https://github.com/screen-share/mouse-events/issues/new) in that repo for extensions you'd like to see made to that spec.
