### ISSUE TITLE
Proposal: Make CaptureController inherit from EventTarget

### ISSUE THREAD

**Issue by eladalon1983** [w3c/mediacapture-screen-share#268]
The [Screen-Capture Mouse Events](https://github.com/screen-share/mouse-events) spec is being prototyped in Chromium by @fred-wang, me, and others. An explanation of what it does is available in its [explainer](https://github.com/screen-share/mouse-events#readme). The issue we're running into is this:
```webidl
partial interface CaptureController {
  attribute EventHandler oncapturedmousechange;
};
```
We'd like [CaptureController](https://www.w3.org/TR/screen-capture/#dom-capturecontroller) to be an [EventTarget](https://dom.spec.whatwg.org/#eventtarget), but that can't be added with partial interfaces, as per [this spec](https://webidl.spec.whatwg.org/#dfn-partial-interface):
> Note: A partial interface definition cannot specify that the interface [inherits](https://webidl.spec.whatwg.org/#dfn-inherit) from another [interface](https://webidl.spec.whatwg.org/#dfn-interface). Inheritance is to be specified on the original interface definition.

It would be helpful if we specified `CaptureController` as inheriting from `EventTarget` right here in the Screen Capture spec. This will help people draft specs that extend CaptureController in useful ways, allowing it to grow beyond its current limited purpose of only supporting [setFocusBehavior()](https://www.w3.org/TR/screen-capture/#dom-capturecontroller-setfocusbehavior).

**Comment by fred-wang** [comment]
Note: This proposed change will have basic test coverage when interfaces/screen-capture.idl is udapted in the WPT repo. In the PR [linked above](https://github.com/web-platform-tests/wpt/pull/40052), this corresponds to the following tests:

screen-capture/idlharness.https.window.js (checking inheritance)
screen-capture/capture-controller-event-target.https.window.js (checking calls to EventTarget on CaptureController)
