### ISSUE TITLE
Should browser area be allowed as “window” surfaceType?  

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-screen-share#27]
This is more of an open question, since I'm not sure about all the security implications.  It might be helpful to define a "browser-window" surfaceType explicitly so user knows that he/she is about to share part of the current webpage.

**Comment by martinthomson** [comment]
We're still struggling with the question of what to do with browser sharing.  My current thought is that sharing the browser (in all forms) would be made somehow more difficult.
