### ISSUE TITLE
Interaction with permissions API

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#28]
We probably need a new string here: https://w3c.github.io/permissions/

Also, we need to understand how we might provide feedback to the permissions API regarding the states they expose.  It might be that we need extra information input (I think we want this) and output (I don't think that we want anything special here).

**Comment by martinthomson** [comment]
We will want to surface whether the site has been "blocked" or whether a user prompt will appear.  Also, sites will want to know if the enhanced permissions required for browser sharing have been granted.  That is special.  We don't want any way to request a permission.

**Comment by alvestrand** [comment]
The name "display" seems like a good one.

**Comment by jan-ivar** [comment]
Fixed by https://github.com/w3c/permissions/pull/184.
