### ISSUE TITLE
Can a shared surface select its derivative window？

### ISSUE THREAD

**Issue by trookie2000** [w3c/mediacapture-screen-share#282]
For example, after clicking the button with the red line shown in the picture, the pop-up window should also be shared
![1699166682938](https://github.com/w3c/mediacapture-screen-share/assets/109945614/95f7b3df-6efe-458d-af15-c54c62169a75)
But now the pop-up is not shared (even though it belongs to the first shared process pop-up).
![image](https://github.com/w3c/mediacapture-screen-share/assets/109945614/41effa6c-b7a4-4e2d-835e-a408c1ce241e)

**Comment by jan-ivar** [comment]
This might be somewhat up to implementations, not the spec, but based on my understanding of implementations today, I'm confident in saying the answer is no.

This is an inherent limitation of "window" sharing (share Entire Desktop as a workaround).

This used to be possible many years ago with "application" sharing, which in Firefox produced a desktop-sized black canvas with every window from the same application.

Multi-window applications seem increasingly rare today, and this was removed in https://github.com/w3c/mediacapture-screen-share/issues/189 for lack of interest. Closing as already considered based on that.
