### ISSUE TITLE
What's needed

### ISSUE THREAD

**Issue by ghost** [w3c/mediacapture-screen-share#284]
Why aren't my text messages and web messages working on my device? I'm no receiving anything to my device. Can you tell if new web doc are needed. I don't appreciate these platforms blocking my device location and causing interferences. If only I could determine what's the block. I keep seeing orange. Does that mean cloud flare or was blocks

**Comment by eladalon1983** [comment]
Thank you for your feedback. We are working to rectify the issue.

**Comment by ghost** [comment]
Please do. Unacceptable. My device is showing as chrome on session. Why?

**Comment by ghost** [comment]
I no longer want to utilize chrome. Please allow my text and web messages
to reach my device
