### ISSUE TITLE
stop navigating from Screenshared browser/window to another shared browser/window

### ISSUE THREAD

**Issue by Agrawal05** [w3c/mediacapture-screen-share#286]
I want the code to stop a person from navigating from Screenshared browser/window to another selected browser/window.

**Comment by eladalon1983** [comment]
It would help if you elaborated your use-case, as currently it's not clear what you mean by "navigate" - does it refer to `alt-tab`, to a mouse-click on a link, or to the user typing a new address in the URL bar?

**Comment by Agrawal05** [comment]
I am working on a project. In which a person has to give a test.I want that when a person is giving the test he should not be able to change his shared screen like should not be able to switch windows, open links, switch tab.

**Comment by Agrawal05** [comment]
I'm working on a project in which user is giving a test and I'm taking screenshot using getDisplayMedia in which user selects the either browser, window or entire screen but I want to restrict user from selecting browser or window I want to share only entire screen. So, right now either it is possible to restrict  user from sharing browser and window or if user shares browser and window then user should not be able to go on the shared tab or window, he should focus on the test window.

**Comment by eladalon1983** [comment]
> I'm taking screenshot using getDisplayMedia

How does the screenshot fit into the scenario of test-taking?

**Comment by Agrawal05** [comment]
As if user changes his screen during test then we will be able to know that where he is going or what he is opening but it is possible only in the case when user select the entire screen to share.

**Comment by eladalon1983** [comment]
So you're not taking a screenshot, you're recording the screen, right?
FYI that users might have multiple screens, btw.

**Comment by alvestrand** [comment]
There have been suggestions of adding a "prevent the user from leaving" function to the Fullscreen API, but the general perception is that the current spec (https://fullscreen.spec.whatwg.org/#security-and-privacy-considerations) should stay in place for the general use case - that the user should never be prevented from leaving fullscreen.

So I think this is unlikely to be acceptable as a generally available UI.

**Comment by eladalon1983** [comment]
> that the user should never be prevented from leaving fullscreen

FWIW, I used to think there'd be value in a fullscreen mode that's harder to get in to but then harder to leave **accidentally** - an extra prompt to go in and out, perhaps. More recently, I've been thinking that cheating-prevention for off-premises exams is a doomed endeavor, as secondary devices are cheap and infeasible to prevent.

**Comment by Agrawal05** [comment]
No, I'm taking screenshot using getDisplayMedia and yeah user has many ways of cheating. I can't stop him but I want to stop him from cheating as much as I can. And I don't want to go in fullscreen mode if I'm taking screenshot.

**Comment by Agrawal05** [comment]
I want the source code of https://wicg.github.io/conditional-focus/demo/ this demo in which if user selects the either browser or window he is not able to go on the shared tab or window.

**Comment by eladalon1983** [comment]
> I want the source code of https://wicg.github.io/conditional-focus/demo/ this demo in which if user selects the either browser or window he is not able to go on the shared tab or window.

Please be aware that in English, "I want X" sounds imperious, which is inappropriate when requesting help.
The source code you seek is [here](https://github.com/WICG/conditional-focus/tree/main/demo). Enjoy!

**Comment by Agrawal05** [comment]
ok thanks, I'll remember it for next time not to use  "I want X". And I'll look into the source code.

**Comment by eladalon1983** [comment]
Awesome.
Shall we close this issue?

**Comment by Agrawal05** [comment]
Umm, no, I need one more help. I'm using this code in Angular, and I'm facing an error - 'Cannot find name 'CaptureController''. I'm encountering this error in the line where I've written 'const controller = new CaptureController();'. If you could assist me with this, it would be really helpful for me. Additionally, if my code could be of help, I can provide it.

**Comment by Agrawal05** [comment]
ok thanks
