### ISSUE TITLE
Inconsistent "hints"

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-screen-share#290]
The [spec](https://w3c.github.io/mediacapture-screen-share/#dictionary-displaymediastreamoptions-members) defines four PreferenceEnums, aka "hints":

<img width="831" alt="image" src="https://github.com/w3c/mediacapture-screen-share/assets/3136226/01c45328-2420-4e6f-8988-242ba52452dd">

But only half of them say _"The User Agent MAY ignore this hint"_. This seems inconsistent, and I don't remember any discussion that might explain this inconsistency.

I think clarifying all four say to _"The User Agent MAY ignore this hint"_ would capture consensus correctly.

**Comment by eladalon1983** [comment]
Fine by me.
