### ISSUE TITLE
Should we have a screenshare extension spec?

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-screen-share#297]
Discussed in the WebRTC editor's meeting today.

If we want the main spec to go to CR, we might want to put new features in an extension spec.
Maybe also move some features that are implemented only in 1 browser in the extension spec as well.

**Comment by youennf** [comment]
It might also be good to label existing issues as either v1 or extensions.

**Comment by jan-ivar** [comment]
Good idea. We've triaged issues with the [enhancement](https://github.com/w3c/mediacapture-screen-share/issues?q=is%3Aissue+is%3Aopen+label%3Aenhancement) label, and they make up 12 out of the 27 open non-editorial issues.

**Comment by eladalon1983** [comment]
Sounds reasonable.

**Comment by jan-ivar** [comment]
That repo is now https://github.com/w3c/mediacapture-screen-share-extensions/
