### ISSUE TITLE
tabid

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#3]
Having the application able to select a sharing target, or to significantly influence the sharing target, was identified in a review to be problematic. An important characteristic of the consent process is that the user selects what is shared, this undermines this.

This might need to be held until we have final UX, which might suggest a way around this.

**Comment by martinthomson** [comment]
@keithgrif:
I'm assuming that no matter what sharing target is selected it can only be shared with user consent? In this way even if an app identifies or suggests a sharing target it cannot happen without user agreement. Is the problematic area the fact that the app could select the share or something else? It would be great to discuss this more and understand the UX possibilities.

**Comment by martinthomson** [comment]
The problem here is that we want to demonstrate intent and avoid the usual problem around interstitial dialogs. Forcing the user to actively select content means that there is a deliberate action taken to initiate the share, as opposed to a largely passive one.

**Comment by keithgrif** [comment]
Yes, the sharing target should only be shared with user consent. The user should never have content shared without their consent. It can be a deliberate user action or request from the sharing application/site.
