### ISSUE TITLE
define behaviors of all existing constraints that should apply in the screen capture

### ISSUE THREAD

**Issue by ShijunS** [w3c/mediacapture-screen-share#31]
At the TPAC session, we decided to clarify the meaning of all the existing constraints that can be applicable to the screen capture.  For example, resolution, framerate, and maybe "exact", etc.  It'd be good to go through the constraint model in the current Media Capture spec so we don't miss anything.

**Comment by martinthomson** [comment]
The document says:

> getDisplayMedia supports all constraints that are defined for use with getUserMedia, however it does not use these constraints to select a specific source or to narrow the set of options for source selection (see 5.2 Constraining Display Surface Selection).

@ShijunS, is this enough for you?

**Comment by ShijunS** [comment]
I'd suggest honoring the frameRate constraint, then ignoring all others.

**Comment by martinthomson** [comment]
I looked through the list of constraints here: https://w3c.github.io/mediacapture-main/getusermedia.html#idl-def-MediaTrackSupportedConstraints

I couldn't see a reason not to support all of these, apart from those that a physically impossible (facingMode, deviceId) and those fit into the existing rules for unsupportable constraints.

**Comment by ShijunS** [comment]
Clearly groupId and sourceType are not applicable either.  

We discussed the resolution topic at TPAC, my recollection is that we don't want to enforce any resolution constraints (e.g. width, height, aspectRatio).  It's up to the end user to pick the display surface.  Meanwhile, it's desirable to keep the captured surface data with the original resolution.  Otherwise, the spec will have to define the constraints in details, which I would not recommend before we get further experience based on implementations as well as feedback from web developers.

**Comment by martinthomson** [comment]
There are two applications of constraints: selection of a source, and shaping of the `MediaStreamTrack`.  The first is out of scope, but the second set is fine.  I think that being able to downscale screen captures will be critical (see also #35).

I don't want to create a situation where we add a "color" (or "colour") constraint that controls the colour space of a captured track and have it unusable in this context without a spec update.

**Comment by ShijunS** [comment]
The current resolution constraints (again, height, width, and aspectRatio) make sense from the webcam perspective given it is the user agent picks the resolution from various native resolutions supported by the webcam devices.  When end user picks the screen or screen region, if the spec would like to have the user agent follow the current resolution constraints, the spec would have to define cropping, scaling, and/or padding, etc. clearly.  

Meanwhile, #35 is a valid question.  If we capture a screen image and render back on the same screen, I expect it should just fit.  So, capturing the logical surface should be the right expectation.  It can be an OS or user agent implementation issue.  The spec can provide a recommendation on that.  But, I don't think that should be done through the constraints.  We can have more discussion under issue #35.

**Comment by jan-ivar** [comment]
I agree with @martinthomson down-scaling is critical. The use-case is obvious: 2880 x 1800 x 60 fps is too rich for most people's uplink.

FWIW Firefox's (non-standard) screen-sharing has supported downscaling since inception ([Try it](https://jsfiddle.net/jib1/76szqnLy/)). However, cropping is not supported (instead all "settings dictionaries" have the same aspect).

However, I find the implicit assumption that all track constraints defined anywhere should work everywhere else absurd. I think we owe implementers to list explicitly the constraints we expect to work on this source. I propose `width`, `height`, and `frameRate`.

I consider `aspectRatio` and `resizeMode` useless (all settings dictionaries have the same aspect).

But I'm open to including them (they'd have some informative value in `track.getSettings()` perhaps.

I propose we don't crop.

**Comment by martinthomson** [comment]
Two things:
1. restore constraints (advise against using them for selection though)
2. go through all of the constraints and see which apply

**Comment by aboba** [comment]
@jan-ivar Can you submit a PR?

**Comment by alvestrand** [comment]
April interim supported bringing constraints back.

**Comment by aboba** [comment]
Consensus from the April interim is for Jan-Ivar to develop a PR along the lines he described. Also, that cropping does not make sense for screen sharing.

**Comment by jan-ivar** [comment]
> restore constraints (advise against using them for selection though)

Covered by # 49.

> go through all of the constraints and see which apply

To be covered by this issue. @suhasHere are you working on a PR? If so, do you have an ETA?

**Comment by alvestrand** [comment]
TPAC discussion was that the PR (#84) was acceptable and should be merged. Closing.
