### ISSUE TITLE
Handle source device pixel ratio

### ISSUE THREAD

**Issue by mhofman** [w3c/mediacapture-screen-share#35]
Issue for discussion started on the list: https://lists.w3.org/Archives/Public/public-media-capture/2015Dec/0029.html

The spec currently doesn't mention anything about how to handle sources (screen, windows) with logical pixels that don't match physical pixels of the monitor.

The most prominent case are "retina displays", which have high density physical pixels. The OS exposes logical pixels that simulate a lower resolution screen and effectively scales things. The scaling factor is usually referred to as "device pixel ratio", at least in the Web world (See [CSS spec](https://drafts.csswg.org/cssom-view/#dom-window-devicepixelratio))

A Mac retina display with a physical size of 2880x1800 usually exposes a virtual resolution of 1440x900. The devicePixelRatio is 2.0 for such monitors.

I believe current implementations simply capture the physical pixels.

When capturing large windows or a full screen, an application might not want a size that large, especially when transmitting to another display with a 1.0 device pixel ratio (effectively zooming the content 200%).

Existing width / height constraints are not adapted to dealing with the resolution in this case:
- There is no way to know the size, physical or logical, of the source selected by the user, making fixed width/height constraints impossible to use
- Max constraints would only limit the size. The content is really meant to be scaled by 2.0, not a floating point number that would make it just fit in the constrained size
- A smaller application window might have a size below the max constraints

One workaround with the state of the current specs could be to:
- gDM
- Read width / height of stream
- use [Window.devicePixelRatio API](https://drafts.csswg.org/cssom-view/#dom-window-devicepixelratio) to guess device pixel ratio of content
- applyConstraints on stream to scale it by that ratio

Unfortunately this might fail on a variety of cases:
- On some multi-monitor systems that have different pixel ratios per monitor (Windows 10), when the browser tab and content captured are on different monitors (Especially because windows can be dragged across monitors, dynamically changing pixel ratios!)
- when the current web app content is zoomed, thus decoupling the CSS devicePixelRatio from the monitor's pixel ratio.

We can solve this by:
- Specifying that the screen share is done using logical pixels only. This might be limiting for apps that would like to capture unscaled screens. It could however be a good default.
- Providing a "constraint" on the `getDeviceMedia` request that would allow the application to indicate whether it wants a stream of logical or physical pixels.
- Optionally, a stream video track attribute, or maybe a stat for the stream, where the application could “read” the current devicePixelRatio for the stream source, irrespective of whether constrained the stream to physical or logical pixels (the app should know what it asked for)

The last point is to know if the captured stream is currently scaled when the app asked for a "logical pixels" stream, or the factor by which to scale it when asking for "physical pixels" and the app wants to do that scaling on its own (e.g. compute a scaling factor adapted to the pixel ratio of the receiving display)

**Comment by mhofman** [comment]
Any suggestion on what to name that constraint?

Any idea on how to expose the current "devicePixelRatio" of the source content? It sounds like this could be in the track settings, but I'm a little unsure as to the implication on capabilities. Is it expected for the settings/capabilities of a track to change without any application action? I guess this happens already when the source changes resolution?

**Comment by mhofman** [comment]
Also wondering what the implication on #33 would be? A composite stream might combine content with different device pixel ratios...

**Comment by mhofman** [comment]
@ShijunS said in #31:

>  If we capture a screen image and render back on the same screen, I expect it should just fit. So, capturing the logical surface should be the right expectation. It can be an OS or user agent implementation issue. The spec can provide a recommendation on that. But, I don't think that should be done through the constraints.

I agree that by default, browsers should capture logical pixels
I just opened Chrome issue https://code.google.com/p/chromium/issues/detail?id=578200 to address this.

I also think that there's benefit to let the application override the default behavior. In some case I might want to transmit the highest resolution possible because I know my environment can handle it.

**Comment by ShijunS** [comment]
I agree this is a valid request.

**Comment by jan-ivar** [comment]
I'm not seeing why logical pixels matter here. It's just a larger resolution video. If I have gigabit internet and a 4K screen to view your retina screen on, why would I want to lose any pixels viewing it?

If the dimensions are too rich for available bandwith, then the downscale factor is based on pixels:
```js
let {width, height} = track.getSettings();
await track.applyConstraints({width: width / factor, height: height / factor});
```

**Comment by jan-ivar** [comment]
Would a fourth option be to downscale retina screens by half by default?

This is perhaps more likely to be what people want, especially for peer connections.

It also simplifies retina detection:
 - `getDisplayMedia({video: true})`
 - Read the existing `track.getSettings().resizeMode`, where `crop-and-scale` means retina.

If so, should we add some prose to this effect in the spec?

**Comment by martinthomson** [comment]
Most of the web treats high DPR displays as though they were downscaled anyway.

Maybe a smart UA could remember that the track has a non-unity DPR and apply the scaling as it encodes, unless there are settings applies that might indicate that the raw bits are desired (min-width or min-height greater than the downscaled size, etc...).  That is, we don't have to erase the extra information as it goes into the pipe, we can just keep in until it pops out somewhere that might not want it.  For instance, media recording might still use the higher ratio, as would a canvas or <video> element, but RTCPeerConnection would probably not.

**Comment by jan-ivar** [comment]
@martinthomson such an abstraction seems confusing, similar to [webkitGetImageDataHD](https://bugs.chromium.org/p/chromium/issues/detail?id=277205).

**Comment by jan-ivar** [comment]
Fixed by https://github.com/w3c/mediacapture-screen-share/pull/84.

**Comment by mhofman** [comment]
Sorry I missed the work going on in #84.

While this is going in the right direction, I have a some concerns the changes don't properly handle some scaling scenarios I originally reported.

The biggest issue is the recommendation to use `window.devicePixelRatio` as a scaling factor. There are some cases where that ratio doesn't correspond to the pixel density of the source (multi-monitor setups on Windows 10, page zoom of the current document).

I would also like to see a way to expose the source pixel ratio of the captured content. Simply reading `window.devicePixelRatio` doesn't work as explained above.
When `resizeMode == "none"`, it would allow the application to know by which factor it should scale / render the content to get back to the original "logical" size.

Here is an example:
I have a super high DPI monitor where the pixel ratio is 5.0
My application would like as high fidelity as possible so it selects `resizemode=none`.
I transmit to another device, or render locally on another monitor, where `window.devicePixelRatio == 2.0`.
My application would like to preserve scale as much as possible and creates a video element which size is `original_size * 2 / 5`.

**Comment by jan-ivar** [comment]
> The biggest issue is the recommendation to use window.devicePixelRatio as a scaling factor. 

Thanks, I'll add a PR to attempt to resolve this. PTAL.

> I would also like to see a way to expose the source pixel ratio of the captured content.

The current workaround for this would be:
```js
const [track] = (await navigator.mediaDevices.getDisplayMedia()).getVideoTracks();
const pixelRatio = track.getCapabilities().max.height / track.getSettings().height;

await track.applyConstraints(myConstraints);
```
I'd recommend opening a new issue if you think this requires its own constraint.

**Comment by mhofman** [comment]
> 
> > I would also like to see a way to expose the source pixel ratio of the captured content.
> 
> The current workaround for this would be:
> 
> ```js
> const [track] = (await navigator.mediaDevices.getDisplayMedia()).getVideoTracks();
> const pixelRatio = track.getCapabilities().max.height / track.getSettings().height;
> 
> await track.applyConstraints(myConstraints);
> ```
> 
> I'd recommend opening a new issue if you think this requires its own constraint.

The use case for this is mostly when using a stream in `resizeMode == none` which means max height == current height. I guess a work around would be cloning the track and applying a resize constraint on it, but that seems insane just to read out the ratio.

I'll open a separate issue to track this.
