### ISSUE TITLE
Make logicalSurface constraint unchangeable

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#36]
@alvestrand notes that logicalSurface could in theory change once a screen capture has been provided.  However, that would be at odds with the advice in the document.

We should make it very clear that logicalSurface is a constraint that selects, just like facingMode.  That is, unlike resolution, once you have a track, it is an unchangeable property and attempts to change it result in overconstraining the track.  This is different to other constraints like width and height in that changing those can be possible once the track is acquired.

We don't have formal language to support making this distinction, I don't know if it is needed though.

**Comment by alvestrand** [comment]
This seems logical to me. My beef was with the language that seemed to imply that there were no selectors.
We have the same language ("won't change after first selection") about deviceId in the mediacapture-main document.

**Comment by martinthomson** [comment]
I think that this is clear enough as it stands.  @alvestrand ?

**Comment by aboba** [comment]
Can we close this issue?
