### ISSUE TITLE
limiting browser sharing to a list of domain/urls

### ISSUE THREAD

**Issue by ikasantsev** [w3c/mediacapture-screen-share#37]
Please consider adding another constraint which will be relevant for OutputCaptureSurfaceType="browser". A commercial product may (and will) need to limit screen sharing to only those tabs which were open from a white-list of domains or even urls. And vice versa - it will be very useful to support a black list of domains/urls (never share contents if a tab is navigated to this address).

**Comment by aboba** [comment]
Decision from TPAC was not to implement whitelists.
