### ISSUE TITLE
Option to exclude cursor from video stream

### ISSUE THREAD

**Issue by mhofman** [w3c/mediacapture-screen-share#38]
Opening spec issue based on [Chrome issue 463423](https://code.google.com/p/chromium/issues/detail?id=463423).

Some applications might want to receive a video stream of the screen share that doesn't include the cursor.
I believe adding a constraint for this would be an easy way to provide this feature.

Where things get trickier is that such applications might want to receive the cursor position programatically instead. This would require extending the `MediaStreamTrack` object to dispatch events about the cursor position.
Furthermore, applications would also want to get the cursor image, which is tricky since not all cursors are simple bitmaps that are alpha blended, some are xoring their background (text selection cursor on windows is the main example)

In #35 I'm already suggesting extending the `MediaStreamTrack` object to expose a "pixel ratio" attribute of the stream. I'm open to alternatives but it sounds like we need a consistent way to expose "metadata" about the screen sharing stream.

**Comment by aboba** [comment]
Is anyone still interested in an option to exclude the cursor?

**Comment by abardik** [comment]
Yes. I moved to use VNC in my current project, because of this and some other issues with Chromium screen capture. So, yes, I need it.

**Comment by fohara** [comment]
Yes, the cursor adds a lot of visual noise which creates difficulties for various use cases (such as monitoring visual activity _excluding_ the cursor).

**Comment by martinthomson** [comment]
Related: What about the caret?

**Comment by martinthomson** [comment]
We should just add a constraint.

**Comment by suhasHere** [comment]
PR : https://github.com/w3c/mediacapture-screen-share/pull/58

**Comment by juberti** [comment]
Might need more than a boolean - possibly an enum: "none, always, only on movement"

**Comment by suhasHere** [comment]
@juberti , is this the right interpretation of your proposal
None or(Never) --> Never capture cursor 
Always --> Always capture the cursor as part of share
On on movement --> Capture cursor when the user moves it

**Comment by juberti** [comment]
yes, exactly

**Comment by suhasHere** [comment]
@juberti  Does #58  address the above idea ?

**Comment by suhasHere** [comment]
closed via #58
