### ISSUE TITLE
non-top-level browsing contexts

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#39]
getUserMedia is getting a sandbox flag: https://github.com/whatwg/html/pull/1211

Do we want one too, or do we instead want to forbid the use of getDisplayMedia from sandboxed iframes entirely?

**Comment by alvestrand** [comment]
to be specific - the flag has been in getusermedia for a while. After discussion with @domenic, we're moving it to HTML.

**Comment by mhofman** [comment]
I don't think we should prevent gDM from sandboxed iframes, the use cases for allowing gUM are the same for allowing gDM.

Is there any reason we can't share the same flag ?

**Comment by martinthomson** [comment]
I will check, but I believe that there is a chance that we will block access to this API from frames entirely.  Why?  Because it's very hard to explain to a user that "example.com" wants something when they are on "other.example.net" and the decision about trust is much more important.

**Comment by ShijunS** [comment]
I'd agree with @mhofman.  We should keep consistency between gDM and gUM in terms of support from sandboxed iframes.  The potential "trust" challenge would be of no difference from that of gUM.  
It'd be an interesting question though as to whether we could share the same flag.

**Comment by alvestrand** [comment]
It would make sense to treat screen capture as a separate permission under the "powerful feature access" spec, which is supposed to control access to powerful features from iframes.

I think browsers should default to not permitting access from iframes in both cases, but it is nice to give the containing iframe separate controls for the two features.

**Comment by ShijunS** [comment]
@Alvestrand, agree on separate iframe controls.

**Comment by mhofman** [comment]
I understand the need for separate controls, but I would like to preserve access to this API from iframes.

There are some valid use cases for them. In particular, imagine a "support" service provider that offers a solution website owners can easily add to their page to offer support capabilities for their customers.
A support solution might be implemented as a sandboxed iframe for example to ensure it doesn't interfere with the page.

IMO, with the feature disabled by default in iframes and requiring a specific flag, if an embedding website includes the flag it indicates an explicit buy in. While the prompt should probably include information about the iframe's origin, from a user point of view, the embedding website is the one that matters to give permission to.

**Comment by martinthomson** [comment]
See feature-policy.

**Comment by aboba** [comment]
Consensus from the April VI is to [use feature policy.](https://www.w3.org/2018/04/12-webrtc-minutes)

**Comment by alvestrand** [comment]
Related to #28

**Comment by aboba** [comment]
@alvestrand What are the next steps on this issue?

**Comment by alvestrand** [comment]
Closing as solved by #87
