### ISSUE TITLE
Elevated consent for browser sharing

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#4]
Looks like the whole elevated consent process, or "Application Permission" is going to be interesting. While Chrome/Blink has decided to go for an application install process, it's likely that Firefox will not.

I think that we need to abstract a little more and just say that there is some special process that is required to grant a site the ability to share the browser.

**Comment by martinthomson** [comment]
@keithgrif:
By "Application Permission" do you mean the fundamental rights of the application to be able to share? I can understand the level of control that an application install process can offer although it does not alone fully mitigate the risk of a rogue app requesting share. An application install process also imposes a level of additional requirement on a share based web app that may not be desirable. Some definition of this process will be needed to state conditions under which a site/app can share.

**Comment by martinthomson** [comment]
I think that for the most part browser UX people will be able to make the right decision. The key here is not to focus on the specifics of the authorization process, but to highlight the importance of it and to note that anything that might be trivially clicked through is generally not sufficient.

**Comment by keithgrif** [comment]
Yes, completely agree and this was a takeaway from the WG meeting.
