### ISSUE TITLE
Disable Local Playback During Audio Sharing

### ISSUE THREAD

**Issue by chenqiang1986** [w3c/mediacapture-screen-share#43]
We want to add a constraint googDisableLocalEcho in the audio part of getUserMedia call.
It only works with audio capturing (either from the whole system or a tab).
If set googDisableLocalEcho:true, then we are going to mute the local playback of the audio being shared.

For example, if one wants to share a tab, and specifies 
getUserMedia({video:..., audio:{mandatory:{sourceId:, googDisableLocalEcho:true}}})
Then during the sharing of the tab, the tab is muted on the sender's side. Otherwise the shared tab is still playing out on the sender's side.

If one wants to share the full screen with system audio and specifies such a parameter. Then we will mute the sender's speaker during the sharing.

**Comment by RByers** [comment]
Most browsers (including chromium) now have a policy against vendor-prefixed APIs.  Any reason this shouldn't be named `disableLocalEcho` instead of `googDisableLocalEcho`?

**Comment by chenqiang1986** [comment]
OK, let's name it as disableLocalEcho.

Thanks.

**Comment by chenqiang1986** [comment]
Is there anything I can do, or any review process so that we can push disableLocalEcho into spec?

**Comment by chenqiang1986** [comment]
I've uploaded the change to spec for disableLocalEcho. Can someone take a look?

**Comment by alvestrand** [comment]
April interim did not show support for this proposal.

**Comment by aboba** [comment]
@alvestrand Should this issue be closed?
