### ISSUE TITLE
Refine "share what is seen"

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#5]
Operating systems with application exclusive modes (Windows 8, virtually all mobile operating systems) cannot easily and reasonably manage things like screen sharing without violating the rule that states that only what is seen is shared.

We need to refine the language around this a little.  There probably needs to be a higher amount of care taken for applications that are shared while not visible, but I don't think that a blanket prohibition is the exact right answer.

**Comment by martinthomson** [comment]
@keithgrif says:
Agree, we should refine this language. It would be good to figure out how significant a use case sharing backgrounded apps will be. Certainly in mobile apps and Win8 the capability is there but will app share in this context be really used? If the app is in the background the user cannot drive the app on a share. I can see use for this for static content and possibly other uses. "Share what is seen" is a good rule as a starting point and we need to cater for exceptions. Perhaps mandatory comfort messaging in the form of a banner or other UE element so that a user is aware that something other than what they are viewing is currently shared?

**Comment by keithgrif** [comment]
The logical and visual display language addresses this in the rewrite. I will review and make some edits on that section based on feedback I got at the W3C meeting.

**Comment by martinthomson** [comment]
@keithgrif, are we ok with closing this?
