### ISSUE TITLE
Clarify 'origin' concept

### ISSUE THREAD

**Issue by stefhak** [w3c/mediacapture-screen-share#53]
From https://lists.w3.org/Archives/Public/public-media-capture/2018Feb/0005.html:
"From Element has its own developed privacy considerations section, particularly focused on origin separation. Is it expected that handling origin separation is to be handled by implementors or is there best practices or implementation guidelines that will be provided?  If the latter, is Feature Policy an applicable solution here?"

**Comment by martinthomson** [comment]
We should add: "Media that is acquired by a given origin is only available to that origin."

**Comment by jan-ivar** [comment]
> From Element has its own developed privacy considerations section

"From element" sounds like https://w3c.github.io/mediacapture-fromelement/ not screen-share, and https://lists.w3.org/Archives/Public/public-media-capture/2018Feb/0005.html: does not appear to mention screen-share...

Was this issue filed on the wrong spec?

Cross-origin violation sadly is a "feature" of screen-sharing, and why it is scary.

@martinthomson double-checking, we gave up on origin-separation here long ago, right?

**Comment by martinthomson** [comment]
That's two different questions.

We need definitely need origin isolation for the stream.  That is, we need to ensure that only the origin that requested the content can look at it.

The notion that we might generate a stream from only same-origin-visible content was abandoned long ago.

**Comment by jan-ivar** [comment]
Do we have that for `getUserMedia`?

**Comment by martinthomson** [comment]
So the implementation does, and we rely on that.  The spec should, and maybe the right way to address this issue is to cite whatever gUM says, and fix gUM if gUM says nothing.

**Comment by aboba** [comment]
This is a getUserMedia problem.
