### ISSUE TITLE
why does getDisplayMedia live on navigator and not navigator.mediaDevices?

### ISSUE THREAD

**Issue by fippo** [w3c/mediacapture-screen-share#55]
apologies if I missed any previous discussion...

Is there a reason for getDisplayMedia living on navigator instead of navigator.mediaDevices?
navigator.getUserMedia is considered legacy so it is somewhat unexpected to see a similar pattern in this spec.

Originally filed as https://github.com/w3c/mediacapture-main/issues/508 but this repository seems more appropriate.

**Comment by alvestrand** [comment]
Reconstructing from memory: I believe the original version was navigator.getUserMedia({video: {device=screencapture}}) - this was deemed too gross and it got changed to navigator.getDisplayMedia. This was after getUserMedia() was targeted to return promises, but before the promise-based version got moved to mediaDevices.
The only *logical* argument I see is that screencaptures are not devices, so placing it on mediaDevices is odd.

**Comment by martinthomson** [comment]
I think that we should just move it to mediaDevices.

**Comment by aboba** [comment]
In the 14 July 2016 draft it was navigator.mediaDevices.getDisplayMedia, but then it was changed to navigator.getDisplayMedia which has already shipped in Edge.

**Comment by alvestrand** [comment]
Conclusion from April 12 VI was that moving it doesn't seem valuable enough to invalidate existing shipped implementations; let it remain where it is.

**Comment by youennf** [comment]
It might be too late but I wonder whether moving it might not be a good idea even for shipping implementations.
Between the time spec is finalized, implementations might be different from what the spec will prescribe, for instance if constraints are brought back and are not supported in shipped implementation.
Migration between older and newer implementations might be easier if using navigator.mediaDevices.

**Comment by aboba** [comment]
Clarifications relating to the operation of constraints should not require moving the method.
