### ISSUE TITLE
TAG review

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-screen-share#59]
Part of the process for shipping stuff is a review by the TAG.
Someone needs to file a ticket and fill in the questionnaires for that.

**Comment by alvestrand** [comment]
Seems to have been opened. https://github.com/w3ctag/design-reviews/issues/309

**Comment by alvestrand** [comment]
Current status seems to be "someone needs to write an explainer from an user perspective" (https://github.com/w3ctag/design-reviews/issues/309#issuecomment-434660180). @uysalere will you do this?

**Comment by jan-ivar** [comment]
[TPAC note](https://www.w3.org/2019/09/18-webrtc-minutes.html#resolution05): Needs horizontal review, fill out privacy and security questionnaire. Need explainer.

@martinthomson Do you want a first stab at this, or have any thoughts on what should go in here? If not I can try to take it.

**Comment by jan-ivar** [comment]
I still need to fill out the privacy questionnaire.
