### ISSUE TITLE
Selecting a Browser Tab for Share

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#6]
@keithgrif says:
A site/app wishing to share needs to advertise a list of applications available to the user. When a browser has multiple tabs open and available the user needs to be able to select which of those tabs they wish to share.

An example is on Windows an app can choose the open list of applications to share as shown in the view below from task manager.
![image](https://cloud.githubusercontent.com/assets/7999602/3935354/8e4eabe2-2494-11e4-91a0-ae946a185837.png)

Note that the browser shows a single application instance. Although multiple tabs are available within the browser  (see image below) the currently selected tab is the only one available in the list.
![image](https://cloud.githubusercontent.com/assets/7999602/3935339/62f8ec50-2494-11e4-80d8-74f65b9d901f.png)

**Comment by martinthomson** [comment]
Informally at least we've settled on sharing windows rather than applications.  For tab selection, I can imagine a nested menu.

**Comment by keithgrif** [comment]
A nested menu would functionally work. Is tab privacy an issue to be addressed? If a specific tab is being shared is it necessary to block or mask other tab titles? Tab share is an important consideration for browser only environment where the only items to share are the browser application, entire monitor/display or specific tabs.

**Comment by martinthomson** [comment]
I imagine that sharing a tab or window would only result in the content of that tab or window being shared.  I wouldn't expect to see any browser chrome in the share.
