### ISSUE TITLE
Define tab capture

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-screen-share#60]
The nonstandard use of getUserMedia for screen capture included the option of capturing from browser tabs. This has proved popular.

The spec should mention that this is a possibility - while tabs can be seen as a special case of "application window", they are mostly perceived as their own thing.

**Comment by niklasenbom** [comment]
Isn't a tab the 'browser' display surface?

**Comment by suhasHere** [comment]
I thought we closed a similar issue on tab sharing as no changes needed for the specification.

Here are the relevant details:

"Consensus from the April VI was for option 2. which requires no change to the specification. See slides here:
https://docs.google.com/presentation/d/1sboQqMc5O1-oZ7w0ZY1VUyhY8JG0VxOzU8kAQitoHJU/edit#slide=id.g32a9278ac5_0_6

@alvestrand  are we opening it up again ?

**Comment by aboba** [comment]
@suhasHere While option 2 doesn’t require a normative change, it probably does require some explanation.

**Comment by alvestrand** [comment]
Current document has in "terminology":

A browser display surface is the rendered form of a single document. This is not strictly limited to HTML [HTML5] documents, though the discussion in this document will address some specific concerns with the capture of HTML.

Suggest adding "The UA may choose to display the current document in a browser window, continuing to cast the current document into the same media stream track when the current document changes. This is commonly called tab capture."

**Comment by dontcallmedom** [comment]
[RESOLUTION](https://www.w3.org/2019/09/18-webrtc-minutes.html#item07): Use 'browsing context' as tab capture
