### ISSUE TITLE
Mention capture of system audio

### ISSUE THREAD

**Issue by alvestrand** [w3c/mediacapture-screen-share#61]
It seems natural that getDisplayMedia({audio: true}) should capture system audio (what would normally be played out on the speakers).

The spec should mention that this is the correct interpretation.

**Comment by aboba** [comment]
That seems like a logical conclusion to me.  The question is how practical it is (e.g. can audio be captured only from a single application or window) and whether implementations plan to support this (the Edge implementation does not).

**Comment by eric-carlson** [comment]
For what it's worth, WebKit/Safari does not plan to capture system audio.

**Comment by uysalere** [comment]
Chrome supports desktop audio capture on Win and CrOS and tab audio capture on all platforms through extensions. I am planning to move this functionality to getDisplayMedia() as well.

**Comment by jianjunz** [comment]
Maybe an API like `getSupportedConstraints` is needed to indicate whether system audio capture is implemented? And will `getDisplayMedia({audio: true, video: false})` being supported?

**Comment by henbos** [comment]
@uysalere With regards to tab audio capture, this sounds very useful to me. I'm holding a presentation, I want to share a video with sounds without echoing the remote participants voices that I can hear but that are not part of the tab.

From a technical perspective, is this very different than what would be required to support window audio capture? Where the window is not a browser tab, but any application window.

**Comment by henbos** [comment]
I listed use cases and came up with a proposal, please take a look:
https://docs.google.com/document/d/1pgN8Pe2zMaD0tytJVsKmnBT-7gM247YlzzWazm7OwSk/edit?usp=sharing

The TL;DR: excludeTabAudio constraint that allows removing the current tab (the tab that called getDisplayMedia())'s audio from the system audio. The choice presented to the user is a yes/no one; do I want to grant permission to share the "speaker's audio"?

**Comment by uysalere** [comment]
> From a technical perspective, is this very different than what would be required to support window audio capture? 

I haven't come across to any OS APIs allowing audio capture for a certain window. But it should be possible to get audio capture for the entire Chrome window. It might be the only selection option.

**Comment by henbos** [comment]
PR exists for what to do about audio in general (very much up to user agent). For the possible echo problems I created a separate issue, #79.

**Comment by alvestrand** [comment]
Done in #78
