### ISSUE TITLE
NavigatorUserMedia no longer exists

### ISSUE THREAD

**Issue by lukebjerring** [w3c/mediacapture-screen-share#63]
Found while authoring https://github.com/web-platform-tests/wpt/pull/12284

`getUserMedia` in `mediacapture-streams` adds directly to `Navigator`.

So, this (mediacapture-screen-share) should be changed to 

    partial interface Navigator {
        Promise<MediaStream> getDisplayMedia(optional MediaStreamConstraints constraints);
    };

**Comment by lukebjerring** [comment]
cc @foolip

**Comment by uysalere** [comment]
This can be a good opportunity to move it to MediaDevices as suggested on https://github.com/w3c/mediacapture-screen-share/issues/55.

**Comment by foolip** [comment]
I'd like to stick to just fixing the IDL problem with this change. Note that the issue was closed and Edge has already shipped it on Navigator, so you'd need to reopen that discussion if you think this is important to change.
