### ISSUE TITLE
MediaTrackConstraints usage contradiction

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-screen-share#67]
5.1 getDisplayMedia definition says using MediaTrackConstraints throws an exception for the sake of not controlling which surface to show, but MediaTrackConstraints contains stuff we might want to support (if we support audio: volume) and other parts of the spec, 5.4, talks about what to do with deviceId, which is part of the MediaTrackConstraints

**Comment by jan-ivar** [comment]
This is fixed by https://github.com/w3c/mediacapture-screen-share/issues/49.
