### ISSUE TITLE
Describe what happens if the window is closed or the monitor is disconnected

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-screen-share#72]
I assume MediaStreamTrack.onmute/onended fires. Is there a GETUSERMEDA section we can reference?

There is also under 6.3 "In addition to feedback mechanisms, a means to for the user to stop any active capture is advisable." - this would be the same type of thing; we should define what the expected behavior is when this happens.

**Comment by aboba** [comment]
It also isn't clear what happens if a window is minimized.  Edge sends black.

**Comment by alvestrand** [comment]
Behavior on minimization should either be "send black" or "resize to 0x0". Black is probably easier to implement.

**Comment by aboba** [comment]
@youenn Can you take this?

**Comment by youennf** [comment]
@aboba, sure will look at it.

**Comment by youennf** [comment]
I looked at the getUserMedia UI currently being implemented:
- Safari has a UI to  mute/unmute capture on a given tab. Video becomes black if muted and relevant mute/unmute events are fired.
- Firefox has a UI to revoke access for a capturing page. Video freezes and an ended event is sent. 
- Chrome has a UI to permanently revoke access for a capturing site. This has no effect on the current page.

The distinction between mute and ended also makes sense in getDisplayMedia:
- A UI disables permanently an ongoing screen capture, a window is closed: ended events make sense.
- A UI allows disabling temporarily screen capture: mute/unmute events make sense.
Window minimization fits nicely in the temporarily disabled bucket: muted events are probably easier to handle by web apps than a 0x0 video stream.

Locked screens fit also well there, especially if the captured display type is not screen.
A UA might also decide to end a track based on some heuristics (amount of time being muted, locked screen...).

I haven't looked precisely at the disconnected screen case but I think it could fit in both buckets.

The screen capture spec could refer to https://w3c.github.io/mediacapture-main/#life-cycle-and-media-flow and provide some informative guidance, for instance:
- Mute a track in reversible conditions. Mention window minimization, locked screen or no way to indicate ongoing capture
- End a track in case of non reversible conditions. Mention: window/application gets closed

**Comment by henbos** [comment]
Will create a PR
