### ISSUE TITLE
Should getDisplayMedia be functional in SecureContext only?

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-screen-share#77]
Following on https://github.com/w3c/webrtc-pc/issues/1945, the question is whether to mandate secure origins for getDisplayMedia.
We could:
- Mandate to reject getDisplayMedia promise for non secure origins
- Make getDisplayMedia SecureContext

**Comment by alvestrand** [comment]
Are these two alternatives?
I think I'd prefer the second, because it's simpler, and corresponds to a lot of other API behaviors.

**Comment by youennf** [comment]
These are alternatives.
I also tend to prefer the second although the first is consistent with existing getUserMedia behavior.
In a perfect world, we could envision moving back getDisplayMedia to navigator.mediaDevices and make mediaDevices SecureContext.

**Comment by martinthomson** [comment]
I also prefer the second.

**Comment by jan-ivar** [comment]
What are the behavioral differences from this choice?

 1. `("getDisplayMedia" in navigator)` is false, e.g. throws `TypeError: ... not a function` vs.
 2. Rejects promise with some error? vs.
 3. something else?

Where "some error" is what, `SecurityError`, `NotAllowedError`, `NotSupportedError`?

Neither Feature Policy nor the Permissions spec seem to mention specific errors.

**Comment by jan-ivar** [comment]
It's 1.

*"An interface, namespace, or member construct is [exposed](https://heycam.github.io/webidl/#dfn-exposed)"* in an insecure context if it's [available in both secure and non secure contexts](https://heycam.github.io/webidl/#available-in-both-secure-and-non-secure-contexts), which boils down to [[SecureContext]](https://heycam.github.io/webidl/#SecureContext) in WebIDL.

**Comment by jan-ivar** [comment]
> Make getDisplayMedia SecureContext

Makes sense to me. This is a new powerful method.

**Comment by cynthia** [comment]
Ping if there was any consensus/decision on this.

**Comment by jan-ivar** [comment]
Yes, see https://github.com/w3c/mediacapture-main/issues/540#issuecomment-434278340.

**Comment by jan-ivar** [comment]
Fixed by https://github.com/w3c/mediacapture-screen-share/pull/86.
