### ISSUE TITLE
The user agent should be allowed to change sources after getDisplayMedia() resolves

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-screen-share#81]
The spec currently has language saying the source is constant after getDisplayMedia() returns a stream, e.g:

> The provided media MUST include precisely one track of each media type in requestedMediaTypes. The devices chosen MUST be the ones determined by the user. Once selected, the source of a MediaStreamTrack MUST NOT change.
> [...]
> Since the source of media cannot be changed after a MediaStreamTrack has been returned and constraints do not affect the selection of display surfaces, these constrainable properties cannot be changed by an application.

This refers to the settings "displaySurface", "logicalSurface" or "cursor" to be constant for a track. I'm not convinced we should enforce these being constants, but even if we do want that we don't have to go so far to say sources are constant, just that sources cannot change type from "logical" to "display" or enable/disable cursor. And just because a user agent (end-user) can change the source doesn't mean that the application has any control of this.

We should allow the user agent to change source on-the-fly. This allows, amongst other things, the user agent to allow the end-user to change which tab ("browser" surface) to present at any given point in time. This is what current extensions are already doing (edit: actually I'm not sure if this is already implemented or just planned to be implemented).

**Comment by alvestrand** [comment]
TPAC discussion concluded to remove the "MUST NOT change" language.

**Comment by jan-ivar** [comment]
I vaguely recall we also decided at TPAC to axe the [displaySurface](https://w3c.github.io/mediacapture-screen-share/#dom-mediatracksettings-displaysurface) and [logicalSurface](https://w3c.github.io/mediacapture-screen-share/#dom-mediatracksettings-logicalsurface) constraints, but I struggle to find it in the minutes. Was it perhaps related to this?

cc @martinthomson

**Comment by aboba** [comment]
@jan-ivar The application cannot use [displaySurface](https://w3c.github.io/mediacapture-screen-share/#dom-mediatracksettings-displaysurface) and [logicalSurface](https://w3c.github.io/mediacapture-screen-share/#dom-mediatracksettings-logicalsurface) constraints to influence what is shared, only to retrieve information after user selection.  Note clear to me that this info is useful though.

**Comment by jan-ivar** [comment]
On `getDisplayMedia` yes, but `track.applyConstraints` still works.

This doesn't matter as long as [displaySurface](https://w3c.github.io/mediacapture-screen-share/#dom-mediatracksettings-displaysurface) and [logicalSurface](https://w3c.github.io/mediacapture-screen-share/#dom-mediatracksettings-logicalsurface) remain constant.

>I'm not convinced we should enforce these being constants,

If they can change, we'd need to figure out what happens if JS succeeds at locking them. E.g.:

```js
await track.applyConstraints({displaySurface: {exact: "browser"}); // say this succeeds
```

Should this bar the user agent from switching to a non-"browser" source?

FWIW I don't see a use-case that requires these to be variable. Implementing an "active tab" source doesn't seem impeded by keeping these constant.

**Comment by eladalon1983** [comment]
> The application cannot use [displaySurface](https://w3c.github.io/mediacapture-screen-share/#dom-mediatracksettings-displaysurface) and [logicalSurface](https://w3c.github.io/mediacapture-screen-share/#dom-mediatracksettings-logicalsurface) constraints to influence what is shared, only to retrieve information after user selection. Note clear to me that this info is useful though.

Practical use of [displaySurface](https://w3c.github.io/mediacapture-screen-share/#dom-mediatracksettings-displaysurface) - I know developers who use video screen-capture as a mechanism for taking a screenshot of the current tab. If the user shares anything but a tab, they can use that information to bail. It would be even more useful if they could also recognize current-tab/other-tab, but that's a different issue; the existing field provides benefit to them.

---

I'll add a PR for removing "MUST NOT change."
