### ISSUE TITLE
Should getDisplayMedia be moved to navigator.mediaDevices

### ISSUE THREAD

**Issue by youennf** [w3c/mediacapture-screen-share#82]
Currently getDisplayMedia is exposed in navigator.
It is more consistent to have getDisplayMedia be part of navigator.mediaDevices.

One potential issue is that Edge shipped already navigator.mediaDevices.

There are some ongoing changes to getDisplayMedia, for instance:
- New handling of constraints
- SecureContext
More changes might come as we make progress.

Given all of this, it might be ok to move it to navigator.mediaDevices.
Some advantages:
- More consistent
- We could envision making mediaDevices SecureContext and would not need to special case getDisplayMedia.

**Comment by fippo** [comment]
see #55

**Comment by aboba** [comment]
Decision at TPAC was to move it.

**Comment by youennf** [comment]
PR https://github.com/w3c/mediacapture-screen-share/pull/86

**Comment by alvestrand** [comment]
Since #86 is merged, closing.
