### ISSUE TITLE
Event for screen sharing

### ISSUE THREAD

**Issue by jianjunz** [w3c/mediacapture-screen-share#83]
Firing an event on tab being shared could notify web application to hide sensitive information or change layout during screen sharing.

Draft of this event could be:

The following event fires on `Document`:

Event name | Interface | Fired when...
-- | -- | --
screensharingchange | `Event` | The tab is started to be shared, or the entire screen is started to be shared and current tab is active. Also fired when screen sharing is stopped.

```
partial interface Document {
  readonly attribute boolean screenSharing;
}
```

Open issues:
1. Web app may be notified after it is being shared. So information leakage may happen before app takes action.
2. `screenSharing` only indicates screen sharing performed by browser.

**Comment by youennf** [comment]
This was discussed during this week call.
This proposal has some drawbacks.

This could be ok with tab sharing but what about screen sharing, and the browser tab moving from one screen to another that is shared/not shared.
Also this would allow any page to observe what another page is doing which might have bad privacy/security side effects.
There is a potential racing issue between this event and actual screen capture, which might make it a bit more difficult to implement correctly.

I think the use case would be better served with something like a css property whose purpose would be to obfuscate a field when screen capture is happening. Not sure how simple this would be to implement. Again, ideally it should probably not be observable from the page using this property. Such behavior might be useful by default for some fields like passwords

One question is whether the use case would benefit for some chrome UI to unobfuscate specific fields?

**Comment by jianjunz** [comment]
> This could be ok with tab sharing but what about screen sharing,

When screen sharing starts, the event is fired on all the tabs that is visible or partially visible in this screen.

> and the browser tab moving from one screen to another that is shared/not shared.

Moving from a shared screen to another not shared screen fires this event, and vice versa.

> Also this would allow any page to observe what another page is doing which might have bad privacy/security side effects.

This event only fires on the tab being shared/not shared.

> There is a potential racing issue between this event and actual screen capture, which might make it a bit more difficult to implement correctly.

Agree. This would be a problem.

If we don't have the requirement to perform non-UI actions(e.g. pause a video) when screen sharing happens, a css property sounds like a good idea to solve this issue.

**Comment by martinthomson** [comment]
I can imagine this becoming permissions-based system, where blocking event propagation is used to deny access to the shared content.  Or the page could black out its content as a result of receiving the event.

Why don't we instead tackle the question of whether we can or should ask sites for their permission before they are shared?

**Comment by jan-ivar** [comment]
Screen sharing is inherently a user-driven feature. If a user wishes to share a web surface, I'm not sure why that's any of that web surface's business. I'm concerned such a feature could be used to subvert screen capture, going against the interest of users, creating unnecessary observer's paradox situations, if you will. 

I'd rather explore having user agents making such decisions, e.g. detect and blur username and password fields,  to protect user privacy in a neutral way.

**Comment by jan-ivar** [comment]
E.g. this might prevent a user from live capturing and recording the activity of a malicious web site for the purposes of gathering evidence. Such evidence would be considered sensitive information from the viewpoint of the malicious site.

**Comment by jianjunz** [comment]
> I can imagine this becoming permissions-based system, where blocking event propagation is used to deny access to the shared content. Or the page could black out its content as a result of receiving the event.
> 
> Why don't we instead tackle the question of whether we can or should ask sites for their permission before they are shared?

In most cases, only a very small part of the page needs to be observed. E.g. password, payment info.



> Screen sharing is inherently a user-driven feature. If a user wishes to share a web surface, I'm not sure why that's any of that web surface's business. I'm concerned such a feature could be used to subvert screen capture, going against the interest of users, creating unnecessary observer's paradox situations, if you will.
> 
> I'd rather explore having user agents making such decisions, e.g. detect and blur username and password fields, to protect user privacy in a neutral way.

I'm wondering if UAs are smart enough to make such decisions. Besides username and password, there might be some site specific sensitive information, such as product keys. Although screen sharing is initialized by user, some content in web pages are dynamically loaded, which is uncertain to the user. For instance, when someone opens a new tab and navigates to Github during screen sharing, he/she doesn't know what recent activities will shown. If there is sensitive information in recent activity, it should be obfuscated.

**Comment by jan-ivar** [comment]
A declarative approach might be better here. Maybe sites could tag things as "sensitive"? This might be useful outside of screen-sharing as well, e.g. the presentation API.

In either case, I sense a potential trust tradeoff here about which party is better at determining things a user finds sensitive vs. a site. A bank for instance may decide to mark everything "sensitive", just because that's simpler for them and their liability, rendering screen sharing of most bank sites unusable. I'm unsure this would lead to the best result for users.

**Comment by jianjunz** [comment]
UAs may prompt user to unobfuscate a sensitive element when it is clicked, like what Chrome is doing for Flash.

**Comment by eladalon1983** [comment]
This issue has not seen any activity in a long time. It appears that, important though it is, it is not important enough to merit action. I am closing this. Feel free to reopen.
