### ISSUE TITLE
getDisplayMedia({video:false}) is interpreted as getDisplayMedia({video:true})

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-screen-share#85]
> 3. Let requestedMediaTypes be the set of media types in constraints with either a dictionary value or a value of true.
> 4. If requestedMediaTypes is the empty set, set requestedMediaTypes to a set containing "video".

The spec does not distinguish the case of "no value" from "false". Because 3) results in an empty set, 4) turns this empty set into the same as "video:true". I don't think this is intentional, let's fix.

**Comment by henbos** [comment]
A side-effect of not fixing this issue would be that {video:false} translates to {video:true}, but {video:false,audio:true} translates to {audio:true}.

Should a request for explicitly no media result in NotFoundError or an OverconstrainedError?

**Comment by henbos** [comment]
Because you are using constraints to constrain the algorithm to fail I think OverconstrainedError is the most correct and consistent with other overconstraining.

**Comment by henbos** [comment]
The title of https://github.com/w3c/mediacapture-screen-share/issues/65 (_Behavior for getDisplayMedia() and getDisplayMedia({}) should be the same_) is not questioned in this issue, only the explicitly setting to false and getting different behavior whether or not audio is included.

**Comment by jan-ivar** [comment]
Thanks @henbos for catching this. I've reopened https://github.com/w3c/mediacapture-screen-share/issues/65#issuecomment-442309841 since I don't see a way to solve this with prose.

**Comment by alvestrand** [comment]
Fixed in #92

**Comment by henbos** [comment]
Fixed by #92
