### ISSUE TITLE
Source pixel ratio of the video track

### ISSUE THREAD

**Issue by mhofman** [w3c/mediacapture-screen-share#89]
This is a follow-up to #35.

Applications that request a non-resized stream (`resizeMode = none`) on high DPI sources will receive a video stream of physical pixels. However such applications would likely need to know what the pixel ratio of the content is when processing it.

For example if the application wants to render the screen capture in a non-zoomed "100% mode" while keeping the highest fidelity on a variety of screens, it would request the capture with resizeMode none but would need to also know the content's logical dimensions to avoid visual scaling when rendering.

The problem I see is how to expose this information. The stream's width and height can be retrieved from the track settings, but there is no settings for "contentPixelRatio", and it probably wouldn't make sense as it's not a directly constrainable property.

To note, the pixel ratio can change during the life of the stream when the user drags the source from one monitor to another.
There doesn't seem to be any event when settings of the track change (especially since such intrinsic changes never trigger over an overconstrained event). In the case of the resizeMode none, the dimensions of the video track would also change, but again, that change isn't directly observable on the stream track object.

**Comment by alvestrand** [comment]
When you say "pixel ratio", are you referring to the scaling usually applied to Retina-type screens, or to the older term referring to non-square pixels?
We have largely stuck to square pixels, since this simplifies things by a *lot*.

I'd think that handling logical dimensions is more of an application function than a WebRTC function.

**Comment by mhofman** [comment]
Correct, I'm referring to retina / high DPI displays.

#84 and #88 Defined what the `resizeMode` constraint does, allowing the application to request a stream of logical pixels by default (i.e. scaled by the source content's pixel ratio), or a stream of unscaled physical pixels (resizeMode = none).

In the later case, the application would usually need to know what the source pixel ratio is (or what the logical dimensions are), so it can do the scaling on its own (e.g. set the size of the video element to the logical dimensions to simulate a 100% zoom)

**Comment by eladalon1983** [comment]
This issue has not seen any activity in a long time. It appears that, important though it is, it is not important enough to merit action. I am closing this. Feel free to reopen.
