### ISSUE TITLE
Hazard with application sharing

### ISSUE THREAD

**Issue by martinthomson** [w3c/mediacapture-screen-share#9]
It's been noted that application sharing comes with certain usability hazards.  We need to either highlight those hazards and explain them, or remove the ability to request an entire application.

**Comment by keithgrif** [comment]
Highlighting the hazards is desirable. Perhaps a way to deal with some of the app sharing hazards would be to provide a level of user control for specifically what they intend to share, even if it is a two step process.

**Comment by martinthomson** [comment]
The current approach simply highlights the hazards.  I also favour removal of "application" from the explicit list, instead preferring to leave the decision to share an application as a whole to the user (or user agent).

**Comment by martinthomson** [comment]
Discussed in Seattle: We will leave this to the browser/user to decide and only offer an "application" option, which will give the user both windows and applications.

**Comment by martinthomson** [comment]
Addressed in #32.
