### ISSUE TITLE
Forbid getDisplayMedia in top-level browsing context by default?

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-screen-share#90]
Right now, [our feature policy](https://w3c.github.io/mediacapture-screen-share/#feature-policy-integration)'s default allowlist is `"self"`, disallowing calls from iframes only.

Since `getDisplayMedia` could be used maliciously to [violate "the Web security model"](https://tools.ietf.org/html/draft-ietf-rtcweb-security-10#section-4.1.1), should it be [`"none"`](https://wicg.github.io/feature-policy/#default-allowlists)?

This would protect web sites with no interest in this API from exposure, e.g. from injection attacks.

cc @youennf, @martinthomson

**Comment by alvestrand** [comment]
This would be a novel concept in the WebRTC context. Can you point to where this has been applied elsewhere in the Web platform?

How would one get access to the function if the default allowlist is "none" - who can grant it, and how?

**Comment by eric-carlson** [comment]
> This would protect web sites with no interest in this API from exposure, e.g. from injection attacks.

Wouldn't this also prevent a developer that is unable to control page headers from using getDisplayMedia?

**Comment by jan-ivar** [comment]
We would be the first in the web platform to use `"none"`.

> Wouldn't this also prevent a developer that is unable to control page headers from using getDisplayMedia?

That would be the idea.

**Comment by martinthomson** [comment]
This would say that you can't get this feature without also opting into feature policy.  If I were more confident about the state of feature policy, I'd say that this is a good idea.

We're still discussing the shortcomings of feature policy, so I am going to say that we need a little more time to consider this.

**Comment by jan-ivar** [comment]
OBE. Would no longer be web compatible.
