### ISSUE TITLE
MediaTrackCapabilities

### ISSUE THREAD

**Issue by henbos** [w3c/mediacapture-screen-share#93]
We've extended MediaTrackConstraintSet and MediaTrackSettings. Should we add a partial dictionary for MediaTrackCapabilities as well?

I'm a little bit confused about similar information being in so many different places and I noticed we don't have this one.

**Comment by alvestrand** [comment]
Yes, you have to.
Having the explanation be done once is a Good Thing, but the IDL has to be in 3 places due to webIDL not being a very powerful language.

**Comment by henbos** [comment]
Removing the interim label, I think this is an editorial issue.
