### ISSUE TITLE
Address corner-cases where getDisplayMedia() shows prompt only to fail afterwards.

### ISSUE THREAD

**Issue by jan-ivar** [w3c/mediacapture-screen-share#96]
Basically, it's a bug in the spec that there are corner cases where calling `getDisplayMedia` will prompt the end user needlessly, only to fail. For instance:
```js
await navigator.mediaDevices.getDisplayMedia({video: {width: {max: 0}}});
```
Fixing this is tricky as it needs to balance 3 things:
 1. **Fingerprinting** - mustn't reveal any device info through re-prodding on failure.
 2. **Interop** - Different UAs may have different downscaling limits (inherently unspec'ed by constraints)
 3. and needless prompting (this issue).

I think we should just leave room in the spec for UAs to optimize away the prompt in these edge-cases, with strict language not to take user configuration into account.

**Comment by alvestrand** [comment]
Jan-Ivar will suggest some language to allow getDisplayMedia() to fail early on constraints that obviously don't make sense.
